<script>
  $(function() {
    var alreadyFilled = false;
    var states = ['Abrantes',
      'Abrantes (São Vicente e São João) e Alferrarede',
      'Aldeia do Mato e Souto',
      'Alvega e Concavada',
      'Bemposta',
      'Carvalhal',
      'Fontes',
      'Martinchel',
      'Mouriscas',
      'Pego',
      'Rio de Moinhos',
      'São Facundo e Vale das Mós',
      'São Miguel do Rio Torto e Rossio ao Sul do Tejo',
      'Tramagal',
      'Águeda',
      'Aguada de Cima',
      'Águeda e Borralha',
      'Barrô e Aguada de Baixo',
      'Belazaima do Chão, Castanheira do Vouga e Agadão',
      'Fermentelos',
      'Macinhata do Vouga',
      'Préstimo e Macieira de Alcoba',
      'Recardães e Espinhel',
      'Travassô e Óis da Ribeira',
      'Trofa, Segadães e Lamas do Vouga',
      'Valongo do Vouga',
      'Aguiar da Beira',
      'Aguiar da Beira e Coruche',
      'Carapito',
      'Cortiçada',
      'Dornelas',
      'Eirado',
      'Forninhos',
      'Pena Verde',
      'Pinheiro',
      'Sequeiros e Gradiz',
      'Souto de Aguiar da Beira e Valverde',
      'Alandroal',
      'Alandroal (Nossa Senhora da Conceição), São Brás dos Matos (Mina do Bugalho) e Juromenha (Nossa Senhora do Loreto)',
      'Capelins (Santo António)',
      'Santiago Maior',
      'Terena (São Pedro)',
      'Albergaria-a-Velha',
      'Albergaria-a-Velha e Valmaior',
      'Alquerubim',
      'Angeja',
      'Branca',
      'Ribeira de Fráguas',
      'São João de Loure e Frossos',
      'Albufeira',
      'Albufeira e Olhos de Água',
      'Ferreiras',
      'Guia',
      'Paderne',
      'Alcácer do Sal',
      'Alcácer do Sal (Santa Maria do Castelo e Santiago) e Santa Susana',
      'Comporta',
      'São Martinho',
      'Torrão',
      'Alcanena',
      'Alcanena e Vila Moreira',
      'Bugalhos',
      'Malhou, Louriceira e Espinheiro',
      'Minde',
      'Moitas Venda',
      'Monsanto',
      'Serra de Santo António',
      'Alcobaça',
      'Alcobaça e Vestiaria',
      'Alfeizerão',
      'Aljubarrota',
      'Bárrio',
      'Benedita',
      'Cela',
      'Coz, Alpedriz e Montes',
      'Évora de Alcobaça',
      'Maiorga',
      'Pataias e Martingança',
      'São Martinho do Porto',
      'Turquel',
      'Vimeiro',
      'Alcochete',
      'Alcochete',
      'Samouco',
      'São Francisco',
      'Alcoutim',
      'Alcoutim e Pereiro',
      'Giões',
      'Martim Longo',
      'Vaqueiros',
      'Alenquer',
      'Abrigada e Cabanas de Torres',
      'Aldeia Galega da Merceana e Aldeia Gavinha',
      'Alenquer (Santo Estêvão e Triana)',
      'Carnota',
      'Carregado e Cadafais',
      'Meca',
      'Olhalvo',
      'Ota',
      'Ribafria e Pereiro de Palhacana',
      'Ventosa',
      'Vila Verde dos Francos',
      'Alfândega da Fé',
      'Agrobom, Saldonha e Vale Pereiro',
      'Alfândega da Fé',
      'Cerejais',
      'Eucisia, Gouveia e Valverde',
      'Ferradosa e Sendim da Serra',
      'Gebelim e Soeima',
      'Parada e Sendim da Ribeira',
      'Pombal e Vales',
      'Sambade',
      'Vilar Chão',
      'Vilarelhos',
      'Vilares de Vilariça',
      'Alijó',
      'Alijó',
      'Carlão e Amieiro',
      'Castedo e Cotas',
      'Favaios',
      'Pegarinhos',
      'Pinhão',
      'Pópulo e Ribalonga',
      'Sanfins do Douro',
      'Santa Eugénia',
      'São Mamede de Ribatua',
      'Vale de Mendiz, Casal de Loivos e Vilarinho de Cotas',
      'Vila Chã',
      'Vila Verde',
      'Vilar de Maçada',
      'Aljezur',
      'Aljezur',
      'Bordeira',
      'Odeceixe',
      'Rogil',
      'Aljustrel',
      'Aljustrel e Rio de Moinhos',
      'Ervidel',
      'Messejana',
      'São João de Negrilhos',
      'Almada',
      'Almada, Cova da Piedade, Pragal e Cacilhas',
      'Caparica e Trafaria',
      'Charneca de Caparica e Sobreda',
      'Costa da Caparica',
      'Laranjeiro e Feijó',
      'Almeida',
      'Almeida',
      'Amoreira, Parada e Cabreira',
      'Azinhal, Peva e Valverde',
      'Castelo Bom',
      'Castelo Mendo, Ade, Monteperobolso e Mesquitela',
      'Freineda',
      'Freixo',
      'Junça e Naves',
      'Leomil, Mido, Senouras e Aldeia Nova',
      'Malhada Sorda',
      'Malpartida e Vale de Coelha',
      'Miuzela e Porto de Ovelha',
      'Nave de Haver',
      'São Pedro de Rio Seco',
      'Vale da Mula',
      'Vilar Formoso',
      'Almeirim',
      'Almeirim',
      'Benfica do Ribatejo',
      'Fazendas de Almeirim',
      'Raposa',
      'Almodôvar',
      'Aldeia dos Fernandes',
      'Almodôvar e Graça dos Padrões',
      'Rosário',
      'Santa Clara-A-Nova e Gomes Aires',
      'Santa Cruz',
      'São Barnabé',
      'Alpiarça',
      'Alpiarça',
      'Alter do Chão',
      'Alter do Chão',
      'Chancelaria',
      'Cunheira',
      'Seda',
      'Alvaiázere',
      'Almoster',
      'Alvaiázere',
      'Maçãs de Dona Maria',
      'Pelmá',
      'Pussos São Pedro',
      'Alvito',
      'Alvito',
      'Vila Nova da Baronia',
      'Amadora',
      'Águas Livres',
      'Alfragide',
      'Encosta do Sol',
      'Falagueira-Venda Nova',
      'Mina de Água',
      'Venteira',
      'Amarante',
      'Aboadela, Sanche e Várzea',
      'Amarante (São Gonçalo), Madalena, Cepelos e Gatão',
      'Ansiães',
      'Bustelo, Carneiro e Carvalho de Rei',
      'Candemil',
      'Figueiró (Santiago e Santa Cristina)',
      'Fregim',
      'Freixo de Cima e de Baixo',
      'Fridão',
      'Gondar',
      'Gouveia (São Simão)',
      'Jazente',
      'Lomba',
      'Louredo',
      'Lufrei',
      'Mancelos',
      'Olo e Canadelo',
      'Padronelo',
      'Rebordelo',
      'Salvador do Monte',
      'Telões',
      'Travanca',
      'Vila Caiz',
      'Vila Chã do Marão',
      'Vila Garcia, Aboim e Chapa',
      'Vila Meã',
      'Amares',
      'Amares e Figueiredo',
      'Barreiros',
      'Bico',
      'Bouro (Santa Maria)',
      'Bouro (Santa Marta)',
      'Caires',
      'Caldelas, Sequeiros e Paranhos',
      'Carrazedo',
      'Dornelas',
      'Ferreiros, Prozelo e Besteiros',
      'Fiscal',
      'Goães',
      'Lago',
      'Rendufe',
      'Torre e Portela',
      'Vilela, Seramil e Paredes Secas',
      'Anadia',
      'Amoreira da Gândara, Paredes do Bairro e Ancas',
      'Arcos e Mogofores',
      'Avelãs de Caminho',
      'Avelãs de Cima',
      'Moita',
      'Sangalhos',
      'São Lourenço do Bairro',
      'Tamengos, Aguim e Óis do Bairro',
      'Vila Nova de Monsarros',
      'Vilarinho do Bairro',
      'Angra do Heroísmo',
      'Altares',
      'Angra (Nossa Senhora da Conceição)',
      'Angra (Santa Luzia)',
      'Angra (São Pedro)',
      'Angra (Sé)',
      'Cinco Ribeiras',
      'Doze Ribeiras',
      'Feteira',
      'Porto Judeu',
      'Posto Santo',
      'Raminho',
      'Ribeirinha',
      'Santa Bárbara',
      'São Bartolomeu de Regatos',
      'São Bento',
      'São Mateus da Calheta',
      'Serreta',
      'Terra Chã',
      'Vila de São Sebastião',
      'Ansião',
      'Alvorge',
      'Ansião',
      'Avelar',
      'Chão de Couce',
      'Pousaflores',
      'Santiago da Guarda',
      'Arcos de Valdevez',
      'Aboim das Choças',
      'Aguiã',
      'Alvora e Loureda',
      'Arcos de Valdevez (Salvador), Vila Fonche e Parada',
      'Arcos de Valdevez (São Paio) e Giela',
      'Ázere',
      'Cabana Maior',
      'Cabreiro',
      'Cendufe',
      'Couto',
      'Eiras e Mei',
      'Gavieira',
      'Gondoriz',
      'Grade e Carralcova',
      'Guilhadeses e Santar',
      'Jolda (Madalena) e Rio Cabrão',
      'Jolda (São Paio)',
      'Miranda',
      'Monte Redondo',
      'Oliveira',
      'Paçô',
      'Padreiro (Salvador e Santa Cristina)',
      'Padroso',
      'Portela e Extremo',
      'Prozelo',
      'Rio de Moinhos',
      'Rio Frio',
      'Sabadim',
      'São Jorge e Ermelo',
      'Senharei',
      'Sistelo',
      'Soajo',
      'Souto e Tabaçô',
      'Távora (Santa Maria e São Vicente)',
      'Vale',
      'Vilela, São Cosme e São Damião e Sá',
      'Arganil',
      'Arganil',
      'Benfeita',
      'Celavisa',
      'Cepos e Teixeira',
      'Cerdeira e Moura da Serra',
      'Côja e Barril de Alva',
      'Folques',
      'Piódão',
      'Pomares',
      'Pombeiro da Beira',
      'São Martinho da Cortiça',
      'Sarzedo',
      'Secarias',
      'Vila Cova de Alva e Anseriz',
      'Armamar',
      'Aldeias',
      'Aricera e Goujoim',
      'Armamar',
      'Cimbres',
      'Folgosa',
      'Fontelo',
      'Queimada',
      'Queimadela',
      'Santa Cruz',
      'São Cosmado',
      'São Martinho das Chãs',
      'São Romão e Santiago',
      'Vacalar',
      'Vila Seca e Santo Adrião',
      'Arouca',
      'Alvarenga',
      'Arouca e Burgo',
      'Cabreiros e Albergaria da Serra',
      'Canelas e Espiunca',
      'Chave',
      'Covelo de Paivó e Janarde',
      'Escariz',
      'Fermedo',
      'Mansores',
      'Moldes',
      'Rossas',
      'Santa Eulália',
      'São Miguel do Mato',
      'Tropeço',
      'Urrô',
      'Várzea',
      'Arraiolos',
      'Arraiolos',
      'Gafanhoeira (São Pedro) e Sabugueiro',
      'Igrejinha',
      'São Gregório e Santa Justa',
      'Vimieiro',
      'Arronches',
      'Assunção',
      'Esperança',
      'Mosteiros',
      'Arruda dos Vinhos',
      'Arranhó',
      'Arruda dos Vinhos',
      'Cardosas',
      'Santiago dos Velhos',
      'Aveiro',
      'Aradas',
      'Cacia',
      'Eixo e Eirol',
      'Esgueira',
      'Glória e Vera Cruz',
      'Oliveirinha',
      'Requeixo, Nossa Senhora de Fátima e Nariz',
      'Santa Joana',
      'São Bernardo',
      'São Jacinto',
      'Avis',
      'Alcórrego e Maranhão',
      'Aldeia Velha',
      'Avis',
      'Benavila e Valongo',
      'Ervedal',
      'Figueira e Barros',
      'Azambuja',
      'Alcoentre',
      'Aveiras de Baixo',
      'Aveiras de Cima',
      'Azambuja',
      'Manique do Intendente, Vila Nova de São Pedro e Maçussa',
      'Vale do Paraíso',
      'Vila Nova da Rainha',
      'B',
      'Baião',
      'Ancede e Ribadouro',
      'Baião (Santa Leocádia) e Mesquinhata',
      'Campelo e Ovil',
      'Frende',
      'Gestaçô',
      'Gove',
      'Grilo',
      'Loivos da Ribeira e Tresouras',
      'Loivos do Monte',
      'Santa Cruz do Douro e São Tomé de Covelas',
      'Santa Marinha do Zêzere',
      'Teixeira e Teixeiró',
      'Valadares',
      'Viariz',
      'Barcelos',
      'Abade de Neiva',
      'Aborim',
      'Adães',
      'Airó',
      'Aldreu',
      'Alheira e Igreja Nova',
      'Alvelos',
      'Alvito (São Pedro e São Martinho) e Couto',
      'Arcozelo',
      'Areias',
      'Areias de Vilar e Encourados',
      'Balugães',
      'Barcelinhos',
      'Barcelos, Vila Boa e Vila Frescainha (São Martinho e São Pedro)',
      'Barqueiros',
      'Cambeses',
      'Campo e Tamel (São Pedro Fins)',
      'Carapeços',
      'Carreira e Fonte Coberta',
      'Carvalhal',
      'Carvalhas',
      'Chorente, Gios, Courel, Pedra Furada e Gueral',
      'Cossourado',
      'Creixomil e Mariz',
      'Cristelo',
      'Durrães e Tregosa',
      'Fornelos',
      'Fragoso',
      'Galegos (Santa Maria)',
      'Galegos (São Martinho)',
      'Gamil e Midões',
      'Gilmonde',
      'Lama',
      'Lijó',
      'Macieira de Rates',
      'Manhente',
      'Martim',
      'Milhazes, Vilar de Figos e Faria',
      'Moure',
      'Negreiros e Chavão',
      'Oliveira',
      'Palme',
      'Panque',
      'Paradela',
      'Pereira',
      'Perelhal',
      'Pousa',
      'Quintiães e Aguiar',
      'Remelhe',
      'Rio Covo (Santa Eugénia)',
      'Roriz',
      'Sequeade e Bastuço (São João e Santo Estevão)',
      'Silva',
      'Silveiros e Rio Covo (Santa Eulália)',
      'Tamel (Santa Leocádia) e Vilar do Monte',
      'Tamel (São Veríssimo)',
      'Ucha',
      'Várzea',
      'Viatodos, Grimancelos, Minhotães e Monte de Fralães',
      'Vila Cova e Feitos',
      'Vila Seca',
      'Barrancos',
      'Barrancos',
      'Barreiro',
      'Alto do Seixalinho, Santo André e Verderena',
      'Barreiro e Lavradio',
      'Palhais e Coina',
      'Santo António da Charneca',
      'Batalha',
      'Batalha',
      'Golpilheira',
      'Reguengo do Fetal',
      'São Mamede',
      'Beja',
      'Albernoa e Trindade',
      'Baleizão',
      'Beja (Salvador e Santa Maria da Feira)',
      'Beja (Santiago Maior e São João Baptista)',
      'Beringel',
      'Cabeça Gorda',
      'Nossa Senhora das Neves',
      'Salvada e Quintos',
      'Santa Clara de Louredo',
      'Santa Vitória e Mombeja',
      'São Matias',
      'Trigaches e São Brissos',
      'Belmonte',
      'Belmonte e Colmeal da Torre',
      'Caria',
      'Inguias',
      'Maçainhas',
      'Benavente',
      'Barrosa',
      'Benavente',
      'Samora Correia',
      'Santo Estêvão',
      'Bombarral',
      'Bombarral e Vale Covo',
      'Carvalhal',
      'Pó',
      'Roliça',
      'Borba',
      'Borba (Matriz)',
      'Borba (São Bartolomeu)',
      'Orada',
      'Rio de Moinhos',
      'Boticas',
      'Alturas do Barroso e Cerdedo',
      'Ardãos e Bobadela',
      'Beça',
      'Boticas e Granja',
      'Codessoso, Curros e Fiães do Tâmega',
      'Covas do Barroso',
      'Dornelas',
      'Pinho',
      'Sapiãos',
      'Vilar e Viveiro',
      'Braga',
      'Adaúfe',
      'Arentim e Cunha',
      'Braga (Maximinos, Sé e Cividade)',
      'Braga (São José de São Lázaro e São João do Souto)',
      'Braga (São Vicente)',
      'Braga (São Vítor)',
      'Cabreiros e Passos (São Julião)',
      'Celeirós, Aveleda e Vimieiro',
      'Crespos e Pousada',
      'Escudeiros e Penso (Santo Estêvão e São Vicente)',
      'Espinho',
      'Esporões',
      'Este (São Pedro e São Mamede)',
      'Ferreiros e Gondizalves',
      'Figueiredo',
      'Gualtar',
      'Guisande e Oliveira (São Pedro)',
      'Lamas',
      'Lomar e Arcos',
      'Merelim (São Paio), Panoias e Parada de Tibães',
      'Merelim (São Pedro) e Frossos',
      'Mire de Tibães',
      'Morreira e Trandeiras',
      'Nogueira, Fraião e Lamaçães',
      'Nogueiró e Tenões',
      'Padim da Graça',
      'Palmeira',
      'Pedralva',
      'Priscos',
      'Real, Dume e Semelhe',
      'Ruilhe',
      'Santa Lucrécia de Algeriz e Navarra',
      'Sequeira',
      'Sobreposta',
      'Tadim',
      'Tebosa',
      'Vilaça e Fradelos',
      'Bragança',
      'Alfaião',
      'Aveleda e Rio de Onor',
      'Babe',
      'Baçal',
      'Carragosa',
      'Castrelos e Carrazedo',
      'Castro de Avelãs',
      'Coelhoso',
      'Donai',
      'Espinhosela',
      'França',
      'Gimonde',
      'Gondesende',
      'Gostei',
      'Grijó de Parada',
      'Izeda, Calvelhe e Paradinha Nova',
      'Macedo do Mato',
      'Mós',
      'Nogueira',
      'Outeiro',
      'Parada e Faílde',
      'Parâmio',
      'Pinela',
      'Quintanilha',
      'Quintela de Lampaças',
      'Rabal',
      'Rebordainhos e Pombares',
      'Rebordãos',
      'Rio Frio e Milhão',
      'Salsas',
      'Samil',
      'Santa Comba de Rossas',
      'São Julião de Palácios e Deilão',
      'São Pedro de Sarracenos',
      'Sé, Santa Maria e Meixedo',
      'Sendas',
      'Serapicos',
      'Sortes',
      'Zoio',
      'C',
      'Cabeceiras de Basto',
      'Abadim',
      'Alvite e Passos',
      'Arco de Baúlhe e Vila Nune',
      'Basto',
      'Bucos',
      'Cabeceiras de Basto',
      'Cavez',
      'Faia',
      'Gondiães e Vilar de Cunhas',
      'Pedraça',
      'Refojos de Basto, Outeiro e Painzela',
      'Rio Douro',
      'Cadaval',
      'Alguber',
      'Cadaval e Pêro Moniz',
      'Lamas e Cercal',
      'Painho e Figueiros',
      'Peral',
      'Vermelha',
      'Vilar',
      'Caldas da Rainha',
      'A dos Francos',
      'Alvorninha',
      'Caldas da Rainha - Nossa Senhora do Pópulo, Coto e São Gregório',
      'Caldas da Rainha - Santo Onofre e Serra do Bouro',
      'Carvalhal Benfeito',
      'Foz do Arelho',
      'Landal',
      'Nadadouro',
      'Salir de Matos',
      'Santa Catarina',
      'Tornada e Salir do Porto',
      'Vidais',
      'Calheta (Açores)',
      'Arco da Calheta',
      'Calheta',
      'Estreito da Calheta',
      'Fajã da Ovelha',
      'Jardim do Mar',
      'Paul do Mar',
      'Ponta do Pargo',
      'Prazeres',
      'Calheta (Madeira)',
      'Calheta',
      'Norte Pequeno',
      'Ribeira Seca',
      'Santo Antão',
      'Topo (Nossa Senhora do Rosário)',
      'Câmara de Lobos',
      'Câmara de Lobos',
      'Curral das Freiras',
      'Estreito de Câmara de Lobos',
      'Jardim da Serra',
      'Quinta Grande',
      'Caminha',
      'Âncora',
      'Arga (Baixo, Cima e São João)',
      'Argela',
      'Caminha (Matriz) e Vilarelho',
      'Dem',
      'Gondar e Orbacém',
      'Lanhelas',
      'Moledo e Cristelo',
      'Riba de Âncora',
      'Seixas',
      'Venade e Azevedo',
      'Vila Praia de Âncora',
      'Vilar de Mouros',
      'Vile',
      'Campo Maior',
      'Nossa Senhora da Expectação',
      'Nossa Senhora da Graça dos Degolados',
      'São João Baptista',
      'Cantanhede',
      'Ançã',
      'Cadima',
      'Cantanhede e Pocariça',
      'Cordinhã',
      'Covões e Camarneira',
      'Febres',
      'Murtede',
      'Ourentã',
      'Portunhos e Outil',
      'Sanguinheira',
      'São Caetano',
      'Sepins e Bolho',
      'Tocha',
      'Vilamar e Corticeiro de Cima',
      'Carrazeda de Ansiães',
      'Amedo e Zedes',
      'Belver e Mogo de Malta',
      'Carrazeda de Ansiães',
      'Castanheiro do Norte e Ribalonga',
      'Fonte Longa',
      'Lavandeira, Beira Grande e Selores',
      'Linhares',
      'Marzagão',
      'Parambos',
      'Pereiros',
      'Pinhal do Norte',
      'Pombal',
      'Seixo de Ansiães',
      'Vilarinho da Castanheira',
      'Carregal do Sal',
      'Beijós',
      'Cabanas de Viriato',
      'Carregal do Sal',
      'Oliveira do Conde',
      'Parada',
      'Cartaxo',
      'Cartaxo e Vale da Pinta',
      'Ereira e Lapa',
      'Pontével',
      'Valada',
      'Vale da Pedra',
      'Vila Chã de Ourique',
      'Cascais',
      'Alcabideche',
      'Carcavelos e Parede',
      'Cascais e Estoril',
      'São Domingos de Rana',
      'Castanheira de Pêra',
      'Castanheira de Pera e Coentral',
      'Castelo Branco',
      'Alcains',
      'Almaceda',
      'Benquerenças',
      'Castelo Branco',
      'Cebolais de Cima e Retaxo',
      'Escalos de Baixo e Mata',
      'Escalos de Cima e Lousa',
      'Freixial e Juncal do Campo',
      'Lardosa',
      'Louriçal do Campo',
      'Malpica do Tejo',
      'Monforte da Beira',
      'Ninho do Açor e Sobral do Campo',
      'Póvoa de Rio de Moinhos e Cafede',
      'Salgueiro do Campo',
      'Santo André das Tojeiras',
      'São Vicente da Beira',
      'Sarzedas',
      'Tinalhas',
      'Castelo de Paiva',
      'Fornos',
      'Raiva, Pedorido e Paraíso',
      'Real',
      'Santa Maria de Sardoura',
      'São Martinho de Sardoura',
      'Sobrado e Bairros',
      'Castelo de Vide',
      'Nossa Senhora da Graça de Póvoa e Meadas',
      'Santa Maria da Devesa',
      'Santiago Maior',
      'São João Baptista',
      'Castro Daire',
      'Almofala',
      'Cabril',
      'Castro Daire',
      'Cujó',
      'Gosende',
      'Mamouros, Alva e Ribolhos',
      'Mezio e Moura Morta',
      'Mões',
      'Moledo',
      'Monteiras',
      'Parada de Ester e Ester',
      'Pepim',
      'Picão e Ermida',
      'Pinheiro',
      'Reriz e Gafanhão',
      'São Joaninho',
      'Castro Marim',
      'Altura',
      'Azinhal',
      'Castro Marim',
      'Odeleite',
      'Castro Verde',
      'Castro Verde e Casével',
      'Entradas',
      'Santa Bárbara de Padrões',
      'São Marcos da Ataboeira',
      'Celorico da Beira',
      'Açores e Velosa',
      'Baraçal',
      'Carrapichana',
      'Casas do Soeiro',
      'Celorico (São Pedro e Santa Maria) e Vila Boa do Mondego',
      'Cortiçô da Serra, Vide Entre Vinhas e Salgueirais',
      'Forno Telheiro',
      'Lajeosa do Mondego',
      'Linhares',
      'Maçal do Chão',
      'Mesquitela',
      'Minhocal',
      'Prados',
      'Rapa e Cadafaz',
      'Ratoeira',
      'Vale de Azares',
      'Celorico de Basto',
      'Agilde',
      'Arnoia',
      'Basto (São Clemente)',
      'Borba de Montanha',
      'Britelo, Gémeos e Ourilhe',
      'Caçarilhe e Infesta',
      'Canedo de Basto e Corgo',
      'Carvalho e Basto (Santa Tecla)',
      'Codeçoso',
      'Fervença',
      'Moreira do Castelo',
      'Rego',
      'Ribas',
      'Vale de Bouro',
      'Veade, Gagos e Molares',
      'Chamusca',
      'Carregueira',
      'Chamusca e Pinheiro Grande',
      'Parreira e Chouto',
      'Ulme',
      'Vale de Cavalos',
      'Chaves',
      'Águas Frias',
      'Anelhe',
      'Bustelo',
      'Calvão e Soutelinho da Raia',
      'Cimo de Vila da Castanheira',
      'Curalha',
      'Eiras, São Julião de Montenegro e Cela',
      'Ervededo',
      'Faiões',
      'Lama de Arcos',
      'Loivos e Póvoa de Agrações',
      'Madalena e Samaiões',
      'Mairos',
      'Moreiras',
      'Nogueira da Montanha',
      'Oura',
      'Outeiro Seco',
      'Paradela',
      'Planalto de Monforte (Oucidres e Bobadela)',
      'Redondelo',
      'Sanfins',
      'Santa Cruz/Trindade e Sanjurge',
      'Santa Leocádia',
      'Santa Maria Maior',
      'Santo António de Monforte',
      'Santo Estêvão',
      'São Pedro de Agostém',
      'São Vicente',
      'Soutelo e Seara Velha',
      'Travancas e Roriz',
      'Tronco',
      'Vale de Anta',
      'Vidago (Vidago, Arcossó, Selhariz e Vilarinho das Paranheiras)',
      'Vila Verde da Raia',
      'Vilar de Nantes',
      'Vilarelho da Raia',
      'Vilas Boas',
      'Vilela do Tâmega',
      'Vilela Seca',
      'Cinfães',
      'Alhões, Bustelo, Gralheira e Ramires',
      'Cinfães',
      'Espadanedo',
      'Ferreiros de Tendais',
      'Fornelos',
      'Moimenta',
      'Nespereira',
      'Oliveira do Douro',
      'Santiago de Piães',
      'São Cristóvão de Nogueira',
      'Souselo',
      'Tarouquela',
      'Tendais',
      'Travanca',
      'Coimbra',
      'Almalaguês',
      'Antuzede e Vil de Matos',
      'Assafarge e Antanhol',
      'Brasfemes',
      'Ceira',
      'Cernache',
      'Coimbra (Sé Nova, Santa Cruz, Almedina e São Bartolomeu)',
      'Eiras e São Paulo de Frades',
      'Santa Clara e Castelo Viegas',
      'Santo António dos Olivais',
      'São João do Campo',
      'São Martinho de Árvore e Lamarosa',
      'São Martinho do Bispo e Ribeira de Frades',
      'São Silvestre',
      'Souselas e Botão',
      'Taveiro, Ameal e Arzila',
      'Torres do Mondego',
      'Trouxemil e Torre de Vilela',
      'Condeixa-a-Nova',
      'Anobra',
      'Condeixa-a-Velha e Condeixa-a-Nova',
      'Ega',
      'Furadouro',
      'Sebal e Belide',
      'Vila Seca e Bem da Fé',
      'Zambujal',
      'Constância',
      'Constância',
      'Montalvo',
      'Santa Margarida da Coutada',
      'Coruche',
      'Biscainho',
      'Branca',
      'Coruche, Fajarda e Erra',
      'Couço',
      'Santana do Mato',
      'São José da Lamarosa',
      'Corvo',
      'O concelho de Vila do Corvo não tem qualquer freguesia.[2]',
      'Covilhã',
      'Aldeia de São Francisco de Assis',
      'Barco e Coutada',
      'Boidobra',
      'Cantar-Galo e Vila do Carvalho',
      'Casegas e Ourondo',
      'Cortes do Meio',
      'Covilhã e Canhoso',
      'Dominguizo',
      'Erada',
      'Ferro',
      'Orjais',
      'Paul',
      'Peraboa',
      'Peso e Vales do Rio',
      'São Jorge da Beira',
      'Sobral de São Miguel',
      'Teixoso e Sarzedo',
      'Tortosendo',
      'Unhais da Serra',
      'Vale Formoso e Aldeia do Souto',
      'Verdelhos',
      'Crato',
      'Aldeia da Mata',
      'Crato e Mártires, Flor da Rosa e Vale do Peso',
      'Gáfete',
      'Monte da Pedra',
      'Cuba',
      'Cuba',
      'Faro do Alentejo',
      'Vila Alva',
      'Vila Ruiva',
      'E',
      'Elvas',
      'Assunção, Ajuda, Salvador e Santo Ildefonso',
      'Barbacena e Vila Fernando',
      'Caia, São Pedro e Alcáçova',
      'Santa Eulália',
      'São Brás e São Lourenço',
      'São Vicente e Ventosa',
      'Terrugem e Vila Boim',
      '',
      'Entroncamento',
      'Nossa Senhora de Fátima',
      'São João Baptista',
      'Espinho',
      'Anta e Guetim',
      'Espinho',
      'Paramos',
      'Silvalde',
      'Esposende',
      'Antas',
      'Apúlia e Fão',
      'Belinho e Mar',
      'Esposende, Marinhas e Gandra',
      'Fonte Boa e Rio Tinto',
      'Forjães',
      'Gemeses',
      'Palmeira de Faro e Curvos',
      'Vila Chã',
      'Estarreja',
      'Avanca',
      'Beduído e Veiros',
      'Canelas e Fermelã',
      'Pardilhó',
      'Salreu',
      'Estremoz',
      'Ameixial (Santa Vitória e São Bento)',
      'Arcos',
      'Estremoz (Santa Maria e Santo André)',
      'Évora Monte (Santa Maria)',
      'Glória',
      'São Bento do Cortiço e Santo Estêvão',
      'São Domingos de Ana Loura',
      'São Lourenço de Mamporcão e São Bento de Ana Loura',
      'Veiros',
      'Évora',
      'Bacelo e Senhora da Saúde',
      'Canaviais',
      'Évora (São Mamede, Sé, São Pedro e Santo Antão)',
      'Malagueira e Horta das Figueiras',
      'Nossa Senhora da Graça do Divor',
      'Nossa Senhora da Tourega e Nossa Senhora de Guadalupe',
      'Nossa Senhora de Machede',
      'São Bento do Mato',
      'São Manços e São Vicente do Pigeiro',
      'São Miguel de Machede',
      'São Sebastião da Giesteira e Nossa Senhora da Boa Fé',
      'Torre de Coelheiros',
      'F',
      'Fafe',
      'Aboim, Felgueiras, Gontim e Pedraído',
      'Agrela e Serafão',
      'Antime e Silvares (São Clemente)',
      'Ardegão, Arnozela e Seidões',
      'Armil',
      'Arões (Santa Cristina)',
      'Arões (São Romão)',
      'Cepães e Fareja',
      'Estorãos',
      'Fafe',
      'Fornelos',
      'Freitas e Vila Cova',
      'Golães',
      'Medelo',
      'Monte e Queimadela',
      'Moreira do Rei e Várzea Cova',
      'Passos',
      'Quinchães',
      'Regadas',
      'Revelhe',
      'Ribeiros',
      'São Gens',
      'Silvares (São Martinho)',
      'Travassós',
      'Vinhós',
      'Faro',
      'Conceição e Estoi',
      'Faro (Sé e São Pedro)',
      'Montenegro',
      'Santa Bárbara de Nexe',
      'Felgueiras',
      'Aião',
      'Airães',
      'Friande',
      'Idães',
      'Jugueiros',
      'Macieira da Lixa e Caramos',
      'Margaride (Santa Eulália), Várzea, Lagares, Varziela e Moure',
      'Pedreira, Rande e Sernande',
      'Penacova',
      'Pinheiro',
      'Pombeiro de Ribavizela',
      'Refontoura',
      'Regilde',
      'Revinhade',
      'Sendim',
      'Torrados e Sousa',
      'Unhão e Lordelo',
      'Vila Cova da Lixa e Borba de Godim',
      'Vila Fria e Vizela (São Jorge)',
      'Vila Verde e Santão',
      'Ferreira do Alentejo',
      'Alfundão e Peroguarda',
      'Ferreira do Alentejo e Canhestros',
      'Figueira dos Cavaleiros',
      'Odivelas',
      'Ferreira do Zêzere',
      'Águas Belas',
      'Areias e Pias',
      'Beco',
      'Chãos',
      'Ferreira do Zêzere',
      'Igreja Nova do Sobral',
      'Nossa Senhora do Pranto',
      'Figueira da Foz',
      'Alhadas',
      'Alqueidão',
      'Bom Sucesso',
      'Buarcos e São Julião',
      'Ferreira-a-Nova',
      'Lavos',
      'Maiorca',
      'Marinha das Ondas',
      'Moinhos da Gândara',
      'Paião',
      'Quiaios',
      'São Pedro',
      'Tavarede',
      'Vila Verde',
      'Figueira de Castelo Rodrigo',
      'Algodres, Vale de Afonsinho e Vilar de Amargo',
      'Almofala e Escarigo',
      'Castelo Rodrigo',
      'Cinco Vilas e Reigada',
      'Colmeal e Vilar Torpim',
      'Escalhão',
      'Figueira de Castelo Rodrigo',
      'Freixeda do Torrão, Quintã de Pêro Martins e Penha de Águia',
      'Mata de Lobos',
      'Vermiosa',
      'Figueiró dos Vinhos',
      'Aguda',
      'Arega',
      'Campelo',
      'Figueiró dos Vinhos e Bairradas',
      'Fornos de Algodres',
      'Algodres',
      'Casal Vasco',
      'Cortiçô e Vila Chã',
      'Figueiró da Granja',
      'Fornos de Algodres',
      'Infias',
      'Juncais, Vila Ruiva e Vila Soeiro do Chão',
      'Maceira',
      'Matança',
      'Muxagata',
      'Queiriz',
      'Sobral Pichorro e Fuinhas',
      'Freixo de Espada à Cinta',
      'Freixo de Espada À Cinta e Mazouco',
      'Lagoaça e Fornos',
      'Ligares',
      'Poiares',
      'Fronteira',
      'Cabeço de Vide',
      'Fronteira',
      'São Saturnino',
      'Funchal',
      'Funchal (Santa Luzia)',
      'Funchal (Santa Maria Maior)',
      'Funchal (São Pedro)',
      'Funchal (Sé)',
      'Imaculado Coração de Maria',
      'Monte',
      'Santo António',
      'São Gonçalo',
      'São Martinho',
      'São Roque',
      'Fundão',
      'Alcaide',
      'Alcaria',
      'Alcongosta',
      'Alpedrinha',
      'Barroca',
      'Bogas de Cima',
      'Capinha',
      'Castelejo',
      'Castelo Novo',
      'Enxames',
      'Fatela',
      'Fundão, Valverde, Donas, Aldeia de Joanes e Aldeia Nova do Cabo',
      'Janeiro de Cima e Bogas de Baixo',
      'Lavacolhos',
      'Orca',
      'Pero Viseu',
      'Póvoa de Atalaia e Atalaia do Campo',
      'Silvares',
      'Soalheira',
      'Souto da Casa',
      'Telhado',
      'Três Povos',
      'Vale de Prazeres e Mata da Rainha',
      'G',
      'Gavião',
      'Belver',
      'Comenda',
      'Gavião e Atalaia',
      'Margem',
      'Góis',
      'Alvares',
      'Cadafaz e Colmeal',
      'Góis',
      'Vila Nova do Ceira',
      'Golegã',
      'Azinhaga',
      'Golegã',
      'Pombalinho',
      'Gondomar',
      'Baguim do Monte (Rio Tinto)',
      'Fânzeres e São Pedro da Cova',
      'Foz do Sousa e Covelo',
      'Gondomar (São Cosme), Valbom e Jovim',
      'Lomba',
      'Melres e Medas',
      'Rio Tinto',
      'Gouveia',
      'Aldeias e Mangualde da Serra',
      'Arcozelo',
      'Cativelos',
      'Figueiró da Serra e Freixo da Serra',
      'Folgosinho',
      'Gouveia',
      'Melo e Nabais',
      'Moimenta da Serra e Vinhó',
      'Nespereira',
      'Paços da Serra',
      'Ribamondego',
      'Rio Torto e Lagarinhos',
      'São Paio',
      'Vila Cortês da Serra',
      'Vila Franca da Serra',
      'Vila Nova de Tazem',
      'Grândola',
      'Azinheira dos Barros e São Mamede do Sádão',
      'Carvalhal',
      'Grândola e Santa Margarida da Serra',
      'Melides',
      'Guarda',
      'Adão',
      'Aldeia do Bispo',
      'Aldeia Viçosa',
      'Alvendre',
      'Arrifana',
      'Avelãs da Ribeira',
      'Avelãs de Ambom e Rocamondo',
      'Benespera',
      'Casal de Cinza',
      'Castanheira',
      'Cavadoude',
      'Codesseiro',
      'Corujeira e Trinta',
      'Faia',
      'Famalicão',
      'Fernão Joanes',
      'Gonçalo',
      'Gonçalo Bocas',
      'Guarda',
      'Jarmelo São Miguel',
      'Jarmelo São Pedro',
      'João Antão',
      'Maçainhas',
      'Marmeleiro',
      'Meios',
      'Mizarela, Pêro Soares e Vila Soeiro',
      'Panoias de Cima',
      'Pega',
      'Pera do Moço',
      'Porto da Carne',
      'Pousade e Albardo',
      'Ramela',
      'Rochoso e Monte Margarida',
      'Santana da Azinha',
      'Sobral da Serra',
      'Vale de Estrela',
      'Valhelhas',
      'Vela',
      'Videmonte',
      'Vila Cortês do Mondego',
      'Vila Fernando',
      'Vila Franca do Deão',
      'Vila Garcia',
      'Guimarães',
      'Abação e Gémeos',
      'Airão Santa Maria, Airão São João e Vermil',
      'Aldão',
      'Arosa e Castelões',
      'Atães e Rendufe',
      'Azurém',
      'Barco',
      'Briteiros Santo Estêvão e Donim',
      'Briteiros São Salvador e Briteiros Santa Leocádia',
      'Brito',
      'Caldelas',
      'Candoso (São Martinho)',
      'Candoso São Tiago e Mascotelos',
      'Conde e Gandarela',
      'Costa',
      'Creixomil',
      'Fermentões',
      'Gonça',
      'Gondar',
      'Guardizela',
      'Infantas',
      'Leitões, Oleiros e Figueiredo',
      'Longos',
      'Lordelo',
      'Mesão Frio',
      'Moreira de Cónegos',
      'Nespereira',
      'Oliveira, São Paio e São Sebastião',
      'Pencelo',
      'Pinheiro',
      'Polvoreira',
      'Ponte',
      'Prazins (Santa Eufémia)',
      'Prazins Santo Tirso e Corvite',
      'Ronfe',
      'Sande (São Martinho)',
      'Sande São Lourenço e Balazar',
      'Sande Vila Nova e Sande São Clemente',
      'São Torcato',
      'Selho (São Cristóvão)',
      'Selho (São Jorge)',
      'Selho São Lourenço e Gominhães',
      'Serzedelo',
      'Serzedo e Calvos',
      'Silvares',
      'Souto Santa Maria, Souto São Salvador e Gondomar',
      'Tabuadelo e São Faustino',
      'Urgezes',
      'H',
      'Horta',
      'Capelo',
      'Castelo Branco',
      'Cedros',
      'Feteira',
      'Flamengos',
      'Horta (Angústias)',
      'Horta (Conceição)',
      'Horta (Matriz)',
      'Pedro Miguel',
      'Praia do Almoxarife',
      'Praia do Norte',
      'Ribeirinha',
      'Salão',
      'I',
      'Idanha-a-Nova',
      'Aldeia de Santa Margarida',
      'Idanha-a-Nova e Alcafozes',
      'Ladoeiro',
      'Medelim',
      'Monfortinho e Salvaterra do Extremo',
      'Monsanto e Idanha-a-Velha',
      'Oledo',
      'Penha Garcia',
      'Proença-A-Velha',
      'Rosmaninhal',
      'São Miguel de Acha',
      'Toulões',
      'Zebreira e Segura',
      'Ílhavo',
      'Gafanha da Encarnação',
      'Gafanha da Nazaré',
      'Gafanha do Carmo',
      'Ílhavo (São Salvador)',
      'L',
      'Lagoa',
      'Estômbar e Parchal',
      'Ferragudo',
      'Lagoa e Carvoeiro',
      'Porches',
      'Lagoa (Açores)',
      'Água de Pau',
      'Cabouco',
      'Lagoa (Nossa Senhora do Rosário)',
      'Lagoa (Santa Cruz)',
      'Ribeira Chã',
      'Lagos',
      'Bensafrim e Barão de São João',
      'Luz',
      'Odiáxere',
      'São Gonçalo de Lagos',
      'Lajes das Flores',
      'Fajã Grande',
      'Fajãzinha',
      'Fazenda',
      'Lajedo',
      'Lajes das Flores',
      'Lomba',
      'Mosteiro',
      'Lajes do Pico',
      'Calheta de Nesquim',
      'Lajes do Pico',
      'Piedade',
      'Ribeiras',
      'Ribeirinha',
      'São João',
      'Lamego',
      'Avões',
      'Bigorne, Magueija e Pretarouca',
      'Britiande',
      'Cambres',
      'Cepões, Meijinhos e Melcões',
      'Ferreirim',
      'Ferreiros de Avões',
      'Figueira',
      'Lalim',
      'Lamego (Almacave e Sé)',
      'Lazarim',
      'Parada do Bispo e Valdigem',
      'Penajoia',
      'Penude',
      'Samodães',
      'Sande',
      'Várzea de Abrunhais',
      'Leiria',
      'Amor',
      'Arrabal',
      'Bajouca',
      'Bidoeira de Cima',
      'Caranguejeira',
      'Coimbrão',
      'Colmeias e Memória',
      'Leiria, Pousos, Barreira e Cortes',
      'Maceira',
      'Marrazes e Barosa',
      'Milagres',
      'Monte Real e Carvide',
      'Monte Redondo e Carreira',
      'Parceiros e Azoia',
      'Regueira de Pontes',
      'Santa Catarina da Serra e Chainça',
      'Santa Eufémia e Boa Vista',
      'Souto da Carpalhosa e Ortigosa',
      'Lisboa',
      'Ajuda',
      'Alcântara',
      'Alvalade',
      'Areeiro',
      'Arroios',
      'Avenidas Novas',
      'Beato',
      'Belém',
      'Benfica',
      'Campo de Ourique',
      'Campolide',
      'Carnide',
      'Estrela',
      'Lumiar',
      'Marvila',
      'Misericórdia',
      'Olivais',
      'Parque das Nações',
      'Penha de França',
      'Santa Clara',
      'Santa Maria Maior',
      'Santo António',
      'São Domingos de Benfica',
      'São Vicente',
      'Loulé',
      'Almancil',
      'Alte',
      'Ameixial',
      'Boliqueime',
      'Loulé (São Clemente)',
      'Loulé (São Sebastião)',
      'Quarteira',
      'Querença, Tôr e Benafim',
      'Salir',
      'Loures',
      'Bucelas',
      'Camarate, Unhos e Apelação',
      'Fanhões',
      'Loures',
      'Lousa',
      'Moscavide e Portela',
      'Sacavém e Prior Velho',
      'Santa Iria de Azoia, São João da Talha e Bobadela',
      'Santo Antão e São Julião do Tojal',
      'Santo António dos Cavaleiros e Frielas',
      'Lourinhã',
      'Lourinhã e Atalaia',
      'Miragaia e Marteleira',
      'Moita dos Ferreiros',
      'Reguengo Grande',
      'Ribamar',
      'Santa Bárbara',
      'São Bartolomeu dos Galegos e Moledo',
      'Vimeiro',
      'Lousã',
      'Foz de Arouce e Casal de Ermio',
      'Gândaras',
      'Lousã e Vilarinho',
      'Serpins',
      'Lousada',
      'Aveleda',
      'Caíde de Rei',
      'Cernadelo e Lousada (São Miguel e Santa Margarida)',
      'Cristelos, Boim e Ordem',
      'Figueiras e Covas',
      'Lodares',
      'Lustosa e Barrosas (Santo Estêvão)',
      'Macieira',
      'Meinedo',
      'Nespereira e Casais',
      'Nevogilde',
      'Silvares, Pias, Nogueira e Alvarenga',
      'Sousela',
      'Torno',
      'Vilar do Torno e Alentém',
      'M',
      'Mação',
      'Amêndoa',
      'Cardigos',
      'Carvoeiro',
      'Envendos',
      'Mação, Penhascoso e Aboboreira',
      'Ortiga',
      'Macedo de Cavaleiros',
      'Ala e Vilarinho do Monte',
      'Amendoeira',
      'Arcas',
      'Bornes e Burga',
      'Carrapatas',
      'Castelãos e Vilar do Monte',
      'Chacim',
      'Cortiços',
      'Corujas',
      'Espadanedo, Edroso, Murçós e Soutelo Mourisco',
      'Ferreira',
      'Grijó',
      'Lagoa',
      'Lamalonga',
      'Lamas',
      'Lombo',
      'Macedo de Cavaleiros',
      'Morais',
      'Olmos',
      'Peredo',
      'Podence e Santa Combinha',
      'Salselas',
      'Sezulfe',
      'Talhas',
      'Talhinhas e Bagueixe',
      'Vale Benfeito',
      'Vale da Porca',
      'Vale de Prados',
      'Vilarinho de Agrochão',
      'Vinhas',
      'Machico',
      'Água de Pena',
      'Caniçal',
      'Machico',
      'Porto da Cruz',
      'Santo António da Serra',
      'Madalena',
      'Bandeiras',
      'Candelária',
      'Criação Velha',
      'Madalena',
      'São Caetano',
      'São Mateus',
      'Mafra',
      'Azueira e Sobral da Abelheira',
      'Carvoeira',
      'Encarnação',
      'Enxara do Bispo, Gradil e Vila Franca do Rosário',
      'Ericeira',
      'Igreja Nova e Cheleiros',
      'Mafra',
      'Malveira e São Miguel de Alcainça',
      'Milharado',
      'Santo Isidoro',
      'Venda do Pinheiro e Santo Estêvão das Galés',
      'Maia',
      'Águas Santas',
      'Castêlo da Maia',
      'Cidade da Maia',
      'Folgosa',
      'Milheirós',
      'Moreira',
      'Nogueira e Silva Escura',
      'Pedrouços',
      'São Pedro Fins',
      'Vila Nova da Telha',
      'Mangualde',
      'Abrunhosa-a-Velha',
      'Alcafache',
      'Cunha Baixa',
      'Espinho',
      'Fornos de Maceira Dão',
      'Freixiosa',
      'Mangualde, Mesquitela e Cunha Alta',
      'Moimenta de Maceira Dão e Lobelhe do Mato',
      'Quintela de Azurara',
      'Santiago de Cassurrães e Póvoa de Cervães',
      'São João da Fresta',
      'Tavares (Chãs, Várzea e Travanca)',
      'Manteigas',
      'Manteigas (Santa Maria)',
      'Manteigas (São Pedro)',
      'Sameiro',
      'Vale de Amoreira',
      'Marco de Canaveses',
      'Alpendorada, Várzea e Torrão',
      'Avessadas e Rosém',
      'Banho e Carvalhosa',
      'Bem Viver',
      'Constance',
      'Marco',
      'Paredes de Viadores e Manhuncelos',
      'Penhalonga e Paços de Gaiolo',
      'Sande e São Lourenço do Douro',
      'Santo Isidoro e Livração',
      'Soalhães',
      'Sobretâmega',
      'Tabuado',
      'Várzea, Aliviada e Folhada',
      'Vila Boa de Quires e Maureles',
      'Vila Boa do Bispo',
      'Marinha Grande',
      'Marinha Grande',
      'Moita',
      'Vieira de Leiria',
      'Marvão',
      'Beirã',
      'Santa Maria de Marvão',
      'Santo António das Areias',
      'São Salvador da Aramenha',
      'Matosinhos',
      'Custóias, Leça do Balio e Guifões',
      'Matosinhos e Leça da Palmeira',
      'Perafita, Lavra e Santa Cruz do Bispo',
      'São Mamede de Infesta e Senhora da Hora',
      'Mealhada',
      'Barcouço',
      'Casal Comba',
      'Luso',
      'Mealhada, Ventosa do Bairro e Antes',
      'Pampilhosa',
      'Vacariça',
      'Mêda',
      'Aveloso',
      'Barreira',
      'Coriscada',
      'Longroiva',
      'Marialva',
      'Mêda, Outeiro de Gatos e Fonte Longa',
      'Poço do Canto',
      'Prova e Casteição',
      'Rabaçal',
      'Ranhados',
      'Vale Flor, Carvalhal e Pai Penela',
      'Melgaço',
      'Alvaredo',
      'Castro Laboreiro e Lamas de Mouro',
      'Chaviães e Paços',
      'Cousso',
      'Cristóval',
      'Fiães',
      'Gave',
      'Paderne',
      'Parada do Monte e Cubalhão',
      'Penso',
      'Prado e Remoães',
      'São Paio',
      'Vila e Roussas',
      'Mértola',
      'Alcaria Ruiva',
      'Corte do Pinto',
      'Espírito Santo',
      'Mértola',
      'Santana de Cambas',
      'São João dos Caldeireiros',
      'São Miguel do Pinheiro, São Pedro de Solis e São Sebastião dos Carros',
      'Mesão Frio',
      'Barqueiros',
      'Cidadelhe',
      'Mesão Frio (Santo André)',
      'Oliveira',
      'Vila Marim',
      'Mira',
      'Carapelhos',
      'Mira',
      'Praia de Mira',
      'Seixo',
      'Miranda do Corvo',
      'Lamas',
      'Miranda do Corvo',
      'Semide e Rio Vide',
      'Vila Nova',
      'Miranda do Douro',
      'Constantim e Cicouro',
      'Duas Igrejas',
      'Genísio',
      'Ifanes e Paradela',
      'Malhadas',
      'Miranda do Douro',
      'Palaçoulo',
      'Picote',
      'Póvoa',
      'São Martinho de Angueira',
      'Sendim e Atenor',
      'Silva e Águas Vivas',
      'Vila Chã de Braciosa',
      'Mirandela',
      'Abambres',
      'Abreiro',
      'Aguieiras',
      'Alvites',
      'Avantos e Romeu',
      'Avidagos, Navalho e Pereira',
      'Barcel, Marmelos e Valverde da Gestosa',
      'Bouça',
      'Cabanelas',
      'Caravelas',
      'Carvalhais',
      'Cedães',
      'Cobro',
      'Fradizela',
      'Franco e Vila Boa',
      'Frechas',
      'Freixeda e Vila Verde',
      'Lamas de Orelhão',
      'Mascarenhas',
      'Mirandela',
      'Múrias',
      'Passos',
      'São Pedro Velho',
      'São Salvador',
      'Suçães',
      'Torre de Dona Chama',
      'Vale de Asnes',
      'Vale de Gouvinhas',
      'Vale de Salgueiro',
      'Vale de Telhas',
      'Mogadouro',
      'Azinhoso',
      'Bemposta',
      'Bruçó',
      'Brunhoso',
      'Brunhozinho, Castanheira e Sanhoane',
      'Castelo Branco',
      'Castro Vicente',
      'Meirinhos',
      'Mogadouro, Valverde, Vale de Porco e Vilar de Rei',
      'Paradela',
      'Penas Roias',
      'Peredo da Bemposta',
      'Remondes e Soutelo',
      'Saldanha',
      'São Martinho do Peso',
      'Tó',
      'Travanca',
      'Urrós',
      'Vale da Madre',
      'Vila de Ala',
      'Vilarinho dos Galegos e Ventozelo',
      'Moimenta da Beira',
      'Alvite',
      'Arcozelos',
      'Baldos',
      'Cabaços',
      'Caria',
      'Castelo',
      'Leomil',
      'Moimenta da Beira',
      'Paradinha e Nagosa',
      'Passô',
      'Pera Velha, Aldeia de Nacomba e Ariz',
      'Peva e Segões',
      'Rua',
      'Sarzedo',
      'Sever',
      'Vilar',
      'Moita',
      'Alhos Vedros',
      'Baixa da Banheira e Vale da Amoreira',
      'Gaio-Rosário e Sarilhos Pequenos',
      'Moita',
      'Monção',
      'Abedim',
      'Anhões e Luzio',
      'Barbeita',
      'Barroças e Taias',
      'Bela',
      'Cambeses',
      'Ceivães e Badim',
      'Lara',
      'Longos Vales',
      'Mazedo e Cortes',
      'Merufe',
      'Messegães, Valadares e Sá',
      'Monção e Troviscoso',
      'Moreira',
      'Pias',
      'Pinheiros',
      'Podame',
      'Portela',
      'Riba de Mouro',
      'Sago, Lordelo e Parada',
      'Segude',
      'Tangil',
      'Troporiz e Lapela',
      'Trute',
      'Monchique',
      'Alferce',
      'Marmelete',
      'Monchique',
      'Mondim de Basto',
      'Atei',
      'Bilhó',
      'Campanhó e Paradança',
      'Ermelo e Pardelhas',
      'São Cristóvão de Mondim de Basto',
      'Vilar de Ferreiros',
      'Monforte',
      'Assumar',
      'Monforte',
      'Santo Aleixo',
      'Vaiamonte',
      'Montalegre',
      'Cabril',
      'Cambeses do Rio, Donões e Mourilhe',
      'Cervos',
      'Chã',
      'Covelo do Gerês',
      'Ferral',
      'Gralhas',
      'Meixedo e Padornelos',
      'Montalegre e Padroso',
      'Morgade',
      'Negrões',
      'Outeiro',
      'Paradela, Contim e Fiães',
      'Pitões das Junias',
      'Reigoso',
      'Salto',
      'Santo André',
      'Sarraquinhos',
      'Sezelhe e Covelães',
      'Solveira',
      'Tourém',
      'Venda Nova e Pondras',
      'Viade de Baixo e Fervidelas',
      'Vila da Ponte',
      'Vilar de Perdizes e Meixide',
      'Montemor-o-Novo',
      'Cabrela',
      'Ciborro',
      'Cortiçadas de Lavre e Lavre',
      'Foros de Vale de Figueira',
      'Nossa Senhora da Vila, Nossa Senhora do Bispo e Silveiras',
      'Santiago do Escoural',
      'São Cristóvão',
      'Montemor-o-Velho',
      'Abrunheira, Verride e Vila Nova da Barca',
      'Arazede',
      'Carapinheira',
      'Ereira',
      'Liceia',
      'Meãs do Campo',
      'Montemor-o-Velho e Gatões',
      'Pereira',
      'Santo Varão',
      'Seixo de Gatões',
      'Tentúgal',
      '',
      'Montijo',
      'Atalaia e Alto Estanqueiro-Jardia',
      'Canha',
      'Montijo e Afonsoeiro',
      'Pegões',
      'Sarilhos Grandes',
      'Mora',
      'Brotas',
      'Cabeção',
      'Mora',
      'Pavia',
      'Mortágua',
      'Cercosa',
      'Espinho',
      'Marmeleira',
      'Mortágua, Vale de Remígio, Cortegaça e Almaça',
      'Pala',
      'Sobral',
      'Trezoi',
      'Moura',
      'Amareleja',
      'Moura (Santo Agostinho e São João Baptista) e Santo Amador',
      'Póvoa de São Miguel',
      'Safara e Santo Aleixo da Restauração',
      'Sobral da Adiça',
      'Mourão',
      'Granja',
      'Luz',
      'Mourão',
      'Murça',
      'Candedo',
      'Carva e Vilares',
      'Fiolhoso',
      'Jou',
      'Murça',
      'Noura e Palheiros',
      'Valongo de Milhais',
      'Murtosa',
      'Bunheiro',
      'Monte',
      'Murtosa',
      'Torreira',
      'N',
      'Nazaré',
      'Famalicão',
      'Nazaré',
      'Valado dos Frades',
      'Nelas',
      'Canas de Senhorim',
      'Carvalhal Redondo e Aguieira',
      'Lapa do Lobo',
      'Nelas',
      'Santar e Moreira',
      'Senhorim',
      'Vilar Seco',
      'Nisa',
      'Alpalhão',
      'Arez e Amieira do Tejo',
      'Espírito Santo, Nossa Senhora da Graça e São Simão',
      'Montalvão',
      'Santana',
      'São Matias',
      'Tolosa',
      'Nordeste',
      'Achada',
      'Achadinha',
      'Algarvia',
      'Lomba da Fazenda',
      'Nordeste',
      'Salga',
      'Santana',
      'Santo António de Nordestinho',
      'São Pedro de Nordestinho',
      'O',
      'Óbidos',
      'A dos Negros',
      'Amoreira',
      'Gaeiras',
      'Olho Marinho',
      'Santa Maria, São Pedro e Sobral da Lagoa',
      'Usseira',
      'Vau',
      'Odemira',
      'Boavista dos Pinheiros',
      'Colos',
      'Longueira/Almograve',
      'Luzianes-Gare',
      'Relíquias',
      'Saboia',
      'Santa Clara-a-Velha',
      'São Luís',
      'São Martinho das Amoreiras',
      'São Salvador e Santa Maria',
      'São Teotónio',
      'Vale de Santiago',
      'Vila Nova de Milfontes',
      'Odivelas',
      'Odivelas',
      'Pontinha e Famões',
      'Póvoa de Santo Adrião e Olival Basto',
      'Ramada e Caneças',
      'Oeiras',
      'Algés, Linda-a-Velha e Cruz Quebrada-Dafundo',
      'Barcarena',
      'Carnaxide e Queijas',
      'Oeiras e São Julião da Barra, Paço de Arcos e Caxias',
      'Porto Salvo',
      'Oleiros',
      'Álvaro',
      'Cambas',
      'Estreito-Vilar Barroco',
      'Isna',
      'Madeirã',
      'Mosteiro',
      'Oleiros-Amieira',
      'Orvalho',
      'Sarnadas de São Simão',
      'Sobral',
      'Olhão',
      'Moncarapacho e Fuseta',
      'Olhão',
      'Pechão',
      'Quelfes',
      'Oliveira de Azeméis',
      'Carregosa',
      'Cesar',
      'Fajões',
      'Loureiro',
      'Macieira de Sarnes',
      'Nogueira do Cravo e Pindelo',
      'Oliveira de Azeméis, Santiago de Riba-Ul, Ul, Macinhata da Seixa e Madail',
      'Ossela',
      'Pinheiro da Bemposta, Travanca e Palmaz',
      'São Martinho da Gândara',
      'São Roque',
      'Vila de Cucujães',
      'Oliveira de Frades',
      'Arca e Varzielas',
      'Arcozelo das Maias',
      'Destriz e Reigoso',
      'Oliveira de Frades, Souto de Lafões e Sejães',
      'Pinheiro',
      'Ribeiradio',
      'São João da Serra',
      'São Vicente de Lafões',
      'Oliveira do Bairro',
      'Bustos, Troviscal e Mamarrosa',
      'Oiã',
      'Oliveira do Bairro',
      'Palhaça',
      'Oliveira do Hospital',
      'Aldeia das Dez',
      'Alvoco das Várzeas',
      'Avô',
      'Bobadela',
      'Ervedal e Vila Franca da Beira',
      'Lagares',
      'Lagos da Beira e Lajeosa',
      'Lourosa',
      'Meruge',
      'Nogueira do Cravo',
      'Oliveira do Hospital e São Paio de Gramaços',
      'Penalva de Alva e São Sebastião da Feira',
      'Santa Ovaia e Vila Pouca da Beira',
      'São Gião',
      'Seixo da Beira',
      'Travanca de Lagos',
      'Ourém',
      'Alburitel',
      'Atouguia',
      'Caxarias',
      'Espite',
      'Fátima',
      'Freixianda, Ribeira do Fárrio e Formigais',
      'Gondemaria e Olival',
      'Matas e Cercal',
      'Nossa Senhora da Piedade',
      'Nossa Senhora das Misericórdias',
      'Rio de Couros e Casal dos Bernardos',
      'Seiça',
      'Urqueira',
      'Ourique',
      'Garvão e Santa Luzia',
      'Ourique',
      'Panoias e Conceição',
      'Santana da Serra',
      'Ovar',
      'Cortegaça',
      'Esmoriz',
      'Maceda',
      'Ovar, São João, Arada e São Vicente de Pereira Jusã',
      'Válega',
      'P',
      'Paços de Ferreira',
      'Carvalhosa',
      'Eiriz',
      'Ferreira',
      'Figueiró',
      'Frazão Arreigada',
      'Freamunde',
      'Meixomil',
      'Paços de Ferreira',
      'Penamaior',
      'Raimonda',
      'Sanfins Lamoso Codessos',
      'Seroa',
      'Palmela',
      'Palmela',
      'Pinhal Novo',
      'Poceirão e Marateca',
      'Quinta do Anjo',
      'Pampilhosa da Serra',
      'Cabril',
      'Dornelas do Zêzere',
      'Fajão-Vidual',
      'Janeiro de Baixo',
      'Pampilhosa da Serra',
      'Pessegueiro',
      'Portela do Fojo-Machio',
      'Unhais-o-Velho',
      'Paredes',
      'Aguiar de Sousa',
      'Astromil',
      'Baltar',
      'Beire',
      'Cete',
      'Cristelo',
      'Duas Igrejas',
      'Gandra',
      'Lordelo',
      'Louredo',
      'Parada de Todeia',
      'Paredes',
      'Rebordosa',
      'Recarei',
      'Sobreira',
      'Sobrosa',
      'Vandoma',
      'Vilela',
      'Paredes de Coura',
      'Agualonga',
      'Bico e Cristelo',
      'Castanheira',
      'Cossourado e Linhares',
      'Coura',
      'Cunha',
      'Formariz e Ferreira',
      'Infesta',
      'Insalde e Porreiras',
      'Mozelos',
      'Padornelo',
      'Parada',
      'Paredes de Coura e Resende',
      'Romarigães',
      'Rubiães',
      'Vascões',
      'Pedrógão Grande',
      'Graça',
      'Pedrógão Grande',
      'Vila Facaia',
      'Penacova',
      'Carvalho',
      'Figueira de Lorvão',
      'Friúmes e Paradela',
      'Lorvão',
      'Oliveira do Mondego e Travanca do Mondego',
      'Penacova',
      'São Pedro de Alva e São Paio de Mondego',
      'Sazes do Lorvão',
      'Penafiel',
      'Abragão',
      'Boelhe',
      'Bustelo',
      'Cabeça Santa',
      'Canelas',
      'Capela',
      'Castelões',
      'Croca',
      'Duas Igrejas',
      'Eja',
      'Fonte Arcada',
      'Galegos',
      'Guilhufe e Urrô',
      'Irivo',
      'Lagares e Figueira',
      'Luzim e Vila Cova',
      'Oldrões',
      'Paço de Sousa',
      'Penafiel',
      'Perozelo',
      'Rans',
      'Recezinhos (São Mamede)',
      'Recezinhos (São Martinho)',
      'Rio de Moinhos',
      'Rio Mau',
      'Sebolido',
      'Termas de São Vicente',
      'Valpedre',
      'Penalva do Castelo',
      'Antas e Matela',
      'Castelo de Penalva',
      'Esmolfe',
      'Germil',
      'Ínsua',
      'Lusinde',
      'Pindo',
      'Real',
      'Sezures',
      'Trancozelos',
      'Vila Cova do Covelo/Mareco',
      'Penamacor',
      'Aldeia do Bispo, Águas e Aldeia de João Pires',
      'Aranhas',
      'Benquerença',
      'Meimão',
      'Meimoa',
      'Pedrógão de São Pedro e Bemposta',
      'Penamacor',
      'Salvador',
      'Vale da Senhora da Póvoa',
      'Penedono',
      'Antas e Ourozinho',
      'Beselga',
      'Castainço',
      'Penedono e Granja',
      'Penela da Beira',
      'Póvoa de Penela',
      'Souto',
      'Penela',
      'Cumeeira',
      'Espinhal',
      'Podentes',
      'São Miguel, Santa Eufémia e Rabaçal',
      'Peniche',
      'Atouguia da Baleia',
      'Ferrel',
      'Peniche',
      'Peso da Régua',
      'Fontelas',
      'Galafura e Covelinhas',
      'Loureiro',
      'Moura Morta e Vinhós',
      'Peso da Régua e Godim',
      'Poiares e Canelas',
      'Sedielos',
      'Vilarinho dos Freires',
      'Pinhel',
      'Agregação das Freguesias Sul de Pinhel',
      'Alto do Palurdo',
      'Alverca da Beira/Bouça Cova',
      'Atalaia e Safurdão',
      'Ervedosa',
      'Freixedas',
      'Lamegal',
      'Lameiras',
      'Manigoto',
      'Pala',
      'Pinhel',
      'Pínzio',
      'Souro Pires',
      'Terras de Massueime',
      'Valbom/Bogalhal',
      'Vale do Coa',
      'Vale do Massueime',
      'Vascoveiro',
      'Pombal',
      'Abiul',
      'Almagreira',
      'Carnide',
      'Carriço',
      'Guia, Ilha e Mata Mourisca',
      'Louriçal',
      'Meirinhas',
      'Pelariga',
      'Pombal',
      'Redinha',
      'Santiago e São Simão de Litém e Albergaria dos Doze',
      'Vermoil',
      'Vila Cã',
      'Ponta Delgada',
      'Ajuda da Bretanha',
      'Arrifes',
      'Candelária',
      'Capelas',
      'Covoada',
      'Fajã de Baixo',
      'Fajã de Cima',
      'Fenais da Luz',
      'Feteiras',
      'Ginetes',
      'Mosteiros',
      'Pilar da Bretanha',
      'Ponta Delgada (São José)',
      'Ponta Delgada (São Pedro)',
      'Ponta Delgada (São Sebastião)',
      'Relva',
      'Remédios',
      'Rosto do Cão (Livramento)',
      'Rosto do Cão (São Roque)',
      'Santa Bárbara',
      'Santa Clara',
      'Santo António',
      'São Vicente Ferreira',
      'Sete Cidades',
      'Ponta do Sol',
      'Canhas',
      'Madalena do Mar',
      'Ponta do Sol',
      'Ponte da Barca',
      'Azias',
      'Boivães',
      'Bravães',
      'Britelo',
      'Crasto, Ruivos e Grovelas',
      'Cuide de Vila Verde',
      'Entre Ambos-os-Rios, Ermida e Germil',
      'Lavradas',
      'Lindoso',
      'Nogueira',
      'Oleiros',
      'Ponte da Barca, Vila Nova de Muía e Paço Vedro de Magalhães',
      'Sampriz',
      'Touvedo (São Lourenço e Salvador)',
      'Vade (São Pedro)',
      'Vade (São Tomé)',
      'Vila Chã (São João Baptista e Santiago)',
      'Ponte de Lima',
      'Anais',
      'Arca e Ponte de Lima',
      'Arcozelo',
      'Ardegão, Freixo e Mato',
      'Associação de Freguesias do Vale do Neiva',
      'Bárrio e Cepões',
      'Beiral do Lima',
      'Bertiandos',
      'Boalhosa',
      'Brandara',
      'Cabaços e Fojo Lobal',
      'Cabração e Moreira do Lima',
      'Calheiros',
      'Calvelo',
      'Correlhã',
      'Estorãos',
      'Facha',
      'Feitosa',
      'Fontão',
      'Fornelos e Queijada',
      'Friastelas',
      'Gandra',
      'Gemieira',
      'Gondufe',
      'Labruja',
      'Labrujó, Rendufe e Vilar do Monte',
      'Navió e Vitorino dos Piães',
      'Poiares',
      'Rebordões (Santa Maria)',
      'Rebordões (Souto)',
      'Refoios do Lima',
      'Ribeira',
      'Sá',
      'Santa Comba',
      'Santa Cruz do Lima',
      'Seara',
      'Serdedelo',
      'Vitorino das Donas',
      'Ponte de Sor',
      'Foros de Arrão',
      'Galveias',
      'Longomel',
      'Montargil',
      'Ponte de Sor, Tramaga e Vale de Açor',
      'Portalegre',
      'Alagoa',
      'Alegrete',
      'Fortios',
      'Reguengo e São Julião',
      'Ribeira de Nisa e Carreiras',
      'Sé e São Lourenço',
      'Urra',
      'Portel',
      'Amieira e Alqueva',
      'Monte do Trigo',
      'Portel',
      'Santana',
      'São Bartolomeu do Outeiro e Oriola',
      'Vera Cruz',
      'Portimão',
      'Alvor',
      'Mexilhoeira Grande',
      'Portimão',
      'Porto',
      'Aldoar, Foz do Douro e Nevogilde',
      'Bonfim',
      'Campanhã',
      'Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória',
      'Lordelo do Ouro e Massarelos',
      'Paranhos',
      'Ramalde',
      'Porto de Mós',
      'Alqueidão da Serra',
      'Alvados e Alcaria',
      'Arrimal e Mendiga',
      'Calvaria de Cima',
      'Juncal',
      'Mira de Aire',
      'Pedreiras',
      'Porto de Mós - São João Baptista e São Pedro',
      'São Bento',
      'Serro Ventoso',
      'Porto Moniz',
      'Achadas da Cruz',
      'Porto Moniz',
      'Ribeira da Janela',
      'Seixal',
      'Porto Santo',
      'Porto Santo',
      'Póvoa de Lanhoso',
      'Águas Santas e Moure',
      'Calvos e Frades',
      'Campos e Louredo',
      'Covelas',
      'Esperança e Brunhais',
      'Ferreiros',
      'Fonte Arcada e Oliveira',
      'Galegos',
      'Garfe',
      'Geraz do Minho',
      'Lanhoso',
      'Monsul',
      'Póvoa de Lanhoso (Nossa Senhora do Amparo)',
      'Rendufinho',
      'Santo Emilião',
      'São João de Rei',
      'Serzedelo',
      'Sobradelo da Goma',
      'Taíde',
      'Travassos',
      'Verim, Friande e Ajude',
      'Vilela',
      'Póvoa de Varzim',
      'Aguçadoura e Navais',
      'Aver-O-Mar, Amorim e Terroso',
      'Balazar',
      'Estela',
      'Laundos',
      'Póvoa de Varzim, Beiriz e Argivai',
      'Rates',
      'Povoação',
      'Água Retorta',
      'Faial da Terra',
      'Furnas',
      'Nossa Senhora dos Remédios',
      'Povoação',
      'Ribeira Quente',
      'Praia da Vitória',
      'Agualva',
      'Biscoitos',
      'Cabo da Praia',
      'Fonte do Bastardo',
      'Fontinhas',
      'Lajes',
      'Porto Martins',
      'Praia da Vitória (Santa Cruz)',
      'Quatro Ribeiras',
      'São Brás',
      'Vila Nova',
      'Proença-a-Nova',
      'Montes da Senhora',
      'Proença-a-Nova e Peral',
      'São Pedro do Esteval',
      'Sobreira Formosa e Alvito da Beira',
      'R',
      'Redondo',
      'Montoito',
      'Redondo',
      'Reguengos de Monsaraz',
      'Campo e Campinho',
      'Corval',
      'Monsaraz',
      'Reguengos de Monsaraz',
      'Resende',
      'Anreade e São Romão de Aregos',
      'Barrô',
      'Cárquere',
      'Felgueiras e Feirão',
      'Freigil e Miomães',
      'Ovadas e Panchorra',
      'Paus',
      'Resende',
      'São Cipriano',
      'São João de Fontoura',
      'São Martinho de Mouros',
      'Ribeira Brava',
      'Campanário',
      'Ribeira Brava',
      'Serra de Água',
      'Tabua',
      'Ribeira de Pena',
      'Alvadia',
      'Canedo',
      'Cerva e Limões',
      'Ribeira de Pena (Salvador) e Santo Aleixo de Além-Tâmega',
      'Santa Marinha',
      'Ribeira Grande',
      'Calhetas',
      'Fenais da Ajuda',
      'Lomba da Maia',
      'Lomba de São Pedro',
      'Maia',
      'Pico da Pedra',
      'Porto Formoso',
      'Rabo de Peixe',
      'Ribeira Grande (Conceição)',
      'Ribeira Grande (Matriz)',
      'Ribeira Seca',
      'Ribeirinha',
      'Santa Bárbara',
      'São Brás',
      'Rio Maior',
      'Alcobertas',
      'Arrouquelas',
      'Asseiceira',
      'Azambujeira e Malaqueijo',
      'Fráguas',
      'Marmeleira e Assentiz',
      'Outeiro da Cortiçada e Arruda dos Pisões',
      'Rio Maior',
      'São João da Ribeira e Ribeira de São João',
      'São Sebastião',
      'S',
      'Sabrosa',
      'Celeirós',
      'Covas do Douro',
      'Gouvinhas',
      'Paços',
      'Parada de Pinhão',
      'Provesende, Gouvães do Douro e São Cristóvão do Douro',
      'Sabrosa',
      'São Lourenço de Ribapinhão',
      'São Martinho de Antas e Paradela de Guiães',
      'Souto Maior',
      'Torre do Pinhão',
      'Vilarinho de São Romão',
      'Sabugal',
      'Águas Belas',
      'Aldeia da Ponte',
      'Aldeia da Ribeira, Vilar Maior e Badamalos',
      'Aldeia do Bispo',
      'Aldeia Velha',
      'Alfaiates',
      'Baraçal',
      'Bendada',
      'Bismula',
      'Casteleiro',
      'Cerdeira',
      'Fóios',
      'Lajeosa e Forcalhos',
      'Malcata',
      'Nave',
      'Pousafoles do Bispo, Pena Lobo e Lomba',
      'Quadrazais',
      'Quintas de São Bartolomeu',
      'Rapoula do Coa',
      'Rebolosa',
      'Rendo',
      'Ruvina, Ruivós e Vale das Éguas',
      'Sabugal e Aldeia de Santo António',
      'Santo Estêvão e Moita',
      'Seixo do Coa e Vale Longo',
      'Sortelha',
      'Souto',
      'Vale de Espinho',
      'Vila Boa',
      'Vila do Touro',
      'Salvaterra de Magos',
      'Glória do Ribatejo e Granho',
      'Marinhais',
      'Muge',
      'Salvaterra de Magos e Foros de Salvaterra',
      'Santa Comba Dão',
      'Ovoa e Vimieiro',
      'Pinheiro de Ázere',
      'Santa Comba Dão e Couto do Mosteiro',
      'São Joaninho',
      'São João de Areias',
      'Treixedo e Nagozela',
      'Santa Cruz',
      'Camacha',
      'Caniço',
      'Gaula',
      'Santa Cruz',
      'Santo António da Serra',
      'Santa Cruz da Graciosa',
      'Guadalupe',
      'Luz',
      'Santa Cruz da Graciosa',
      'São Mateus',
      'Santa Cruz das Flores',
      'Caveira',
      'Cedros',
      'Ponta Delgada',
      'Santa Cruz das Flores',
      'Santa Maria da Feira',
      'Argoncilhe',
      'Arrifana',
      'Caldas de São Jorge e Pigeiros',
      'Canedo, Vale e Vila Maior',
      'Escapães',
      'Fiães',
      'Fornos',
      'Lobão, Gião, Louredo e Guisande',
      'Lourosa',
      'Milheirós de Poiares',
      'Mozelos',
      'Nogueira da Regedoura',
      'Paços de Brandão',
      'Rio Meão',
      'Romariz',
      'Sanguedo',
      'Santa Maria da Feira, Travanca, Sanfins e Espargo',
      'Santa Maria de Lamas',
      'São João de Ver',
      'São Miguel do Souto e Mosteirô',
      'São Paio de Oleiros',
      'Santa Marta de Penaguião',
      'Alvações do Corgo',
      'Cumieira',
      'Fontes',
      'Lobrigos (São Miguel e São João Baptista) e Sanhoane',
      'Louredo e Fornelos',
      'Medrões',
      'Sever',
      'Santana',
      'Arco de São Jorge',
      'Faial',
      'Ilha',
      'Santana',
      'São Jorge',
      'São Roque do Faial',
      'Santarém',
      'Abitureiras',
      'Abrã',
      'Achete, Azoia de Baixo e Póvoa de Santarém',
      'Alcanede',
      'Alcanhões',
      'Almoster',
      'Amiais de Baixo',
      'Arneiro das Milhariças',
      'Azoia de Cima e Tremês',
      'Casével e Vaqueiros',
      'Gançaria',
      'Moçarria',
      'Pernes',
      'Póvoa da Isenta',
      'Romeira e Várzea',
      'Santarém (Marvila), Santa Iria da Ribeira de Santarém, Santarém (São Salvador) e Santarém (São Nicolau)',
      'São Vicente do Paul e Vale de Figueira',
      'Vale de Santarém',
      'Santiago do Cacém',
      'Abela',
      'Alvalade',
      'Cercal',
      'Ermidas-Sado',
      'Santiago do Cacém, Santa Cruz e São Bartolomeu da Serra',
      'Santo André',
      'São Domingos e Vale de Água',
      'São Francisco da Serra',
      'Santo Tirso',
      'Agrela',
      'Água Longa',
      'Areias, Sequeiró, Lama e Palmeira',
      'Aves',
      'Carreira e Refojos de Riba de Ave',
      'Lamelas e Guimarei',
      'Monte Córdova',
      'Negrelos (São Tomé)',
      'Rebordões',
      'Reguenga',
      'Roriz',
      'Santo Tirso, Couto (Santa Cristina e São Miguel) e Burgães',
      'Vila Nova do Campo',
      'Vilarinho',
      'São Brás de Alportel',
      'São Brás de Alportel',
      'São João da Madeira',
      'São João da Madeira',
      'São João da Pesqueira',
      'Castanheiro do Sul',
      'Ervedosa do Douro',
      'Nagozelo do Douro',
      'Paredes da Beira',
      'Riodades',
      'São João da Pesqueira e Várzea de Trevões',
      'Soutelo do Douro',
      'Trevões e Espinhosa',
      'Vale de Figueira',
      'Valongo dos Azeites',
      'Vilarouco e Pereiros',
      '',
      'São Pedro do Sul',
      'Bordonhos',
      'Carvalhais e Candal',
      'Figueiredo de Alva',
      'Manhouce',
      'Pindelo dos Milagres',
      'Pinho',
      'Santa Cruz da Trapa e São Cristóvão de Lafões',
      'São Félix',
      'São Martinho das Moitas e Covas do Rio',
      'São Pedro do Sul, Várzea e Baiões',
      'Serrazes',
      'Sul',
      'Valadares',
      'Vila Maior',
      'São Roque do Pico',
      'Prainha',
      'Santa Luzia',
      'Santo Amaro',
      'Santo António',
      'São Roque do Pico',
      'São Vicente (Madeira)',
      'Boa Ventura',
      'Ponta Delgada',
      'São Vicente',
      'Sardoal',
      'Alcaravela',
      'Santiago de Montalegre',
      'Sardoal',
      'Valhascos',
      'Sátão',
      'Águas Boas e Forles',
      'Avelal',
      'Ferreira de Aves',
      'Mioma',
      'Rio de Moinhos',
      'Romãs, Decermilo e Vila Longa',
      'São Miguel de Vila Boa',
      'Sátão',
      'Silvã de Cima',
      'Seia',
      'Alvoco da Serra',
      'Carragozela e Várzea de Meruge',
      'Girabolhos',
      'Loriga',
      'Paranhos',
      'Pinhanços',
      'Sabugueiro',
      'Sameice e Santa Eulália',
      'Sandomil',
      'Santa Comba',
      'Santa Marinha e São Martinho',
      'Santiago',
      'Sazes da Beira',
      'Seia, São Romão e Lapa dos Dinheiros',
      'Teixeira',
      'Torrozelo e Folhadosa',
      'Tourais e Lajes',
      'Travancinha',
      'Valezim',
      'Vide e Cabeça',
      'Vila Cova à Coelheira',
      'Seixal',
      'Amora',
      'Corroios',
      'Fernão Ferro',
      'Seixal, Arrentela e Aldeia de Paio Pires',
      'Sernancelhe',
      'Arnas',
      'Carregal',
      'Chosendo',
      'Cunha',
      'Faia',
      'Ferreirim e Macieira',
      'Fonte Arcada e Escurquela',
      'Granjal',
      'Lamosa',
      'Penso e Freixinho',
      'Quintela',
      'Sernancelhe e Sarzeda',
      'Vila da Ponte',
      'Serpa',
      'Brinches',
      'Pias',
      'Serpa (Salvador e Santa Maria)',
      'Vila Nova de São Bento e Vale de Vargo',
      'Vila Verde de Ficalho',
      'Sertã',
      'Cabeçudo',
      'Carvalhal',
      'Castelo',
      'Cernache do Bonjardim, Nesperal e Palhais',
      'Cumeada e Marmeleiro',
      'Ermida e Figueiredo',
      'Pedrógão Pequeno',
      'Sertã',
      'Troviscal',
      'Várzea dos Cavaleiros',
      'Sesimbra',
      'Quinta do Conde',
      'Sesimbra (Castelo)',
      'Sesimbra (Santiago)',
      'Setúbal',
      'Azeitão (São Lourenço e São Simão)',
      'Gâmbia-Pontes-Alto da Guerra',
      'Sado',
      'Setúbal (São Julião, Nossa Senhora da Anunciada e Santa Maria da Graça)',
      'Setúbal (São Sebastião)',
      'Sever do Vouga',
      'Cedrim e Paradela',
      'Couto de Esteves',
      'Pessegueiro do Vouga',
      'Rocas do Vouga',
      'Sever do Vouga',
      'Silva Escura e Dornelas',
      'Talhadas',
      'Silves',
      'Alcantarilha e Pera',
      'Algoz e Tunes',
      'Armação de Pera',
      'São Bartolomeu de Messines',
      'São Marcos da Serra',
      'Silves',
      'Sines',
      'Porto Covo',
      'Sines',
      'Sintra',
      'Agualva e Mira-Sintra',
      'Algueirão-Mem Martins',
      'Almargem do Bispo, Pero Pinheiro e Montelavar',
      'Cacém e São Marcos',
      'Casal de Cambra',
      'Colares',
      'Massamá e Monte Abraão',
      'Queluz e Belas',
      'Rio de Mouro',
      'São João das Lampas e Terrugem',
      'Sintra (Santa Maria e São Miguel, São Martinho e São Pedro de Penaferrim)',
      'Sobral de Monte Agraço',
      'Santo Quintino',
      'Sapataria',
      'Sobral de Monte Agraço',
      'Soure',
      'Alfarelos',
      'Degracias e Pombalinho',
      'Figueiró do Campo',
      'Gesteira e Brunhós',
      'Granja do Ulmeiro',
      'Samuel',
      'Soure',
      'Tapéus',
      'Vila Nova de Anços',
      'Vinha da Rainha',
      'Sousel',
      'Cano',
      'Casa Branca',
      'Santo Amaro',
      'Sousel',
      'T',
      'Tábua',
      'Ázere e Covelo',
      'Candosa',
      'Carapinha',
      'Covas e Vila Nova de Oliveirinha',
      'Espariz e Sinde',
      'Midões',
      'Mouronho',
      'Pinheiro de Coja e Meda de Mouros',
      'Póvoa de Midões',
      'São João da Boa Vista',
      'Tábua',
      'Tabuaço',
      'Adorigo',
      'Arcos',
      'Barcos e Santa Leocádia',
      'Chavães',
      'Desejosa',
      'Granja do Tedo',
      'Longa',
      'Paradela e Granjinha',
      'Pinheiros e Vale de Figueira',
      'Sendim',
      'Tabuaço',
      'Távora e Pereiro',
      'Valença do Douro',
      'Tarouca',
      'Gouviães e Ucanha',
      'Granja Nova e Vila Chã da Beira',
      'Mondim da Beira',
      'Salzedas',
      'São João de Tarouca',
      'Tarouca e Dálvares',
      'Várzea da Serra',
      'Tavira',
      'Cachopo',
      'Conceição e Cabanas de Tavira',
      'Luz de Tavira e Santo Estêvão',
      'Santa Catarina da Fonte do Bispo',
      'Santa Luzia',
      'Tavira (Santa Maria e Santiago)',
      'Terras de Bouro',
      'Balança',
      'Campo do Gerês',
      'Carvalheira',
      'Chamoim e Vilar',
      'Chorense e Monte',
      'Cibões e Brufe',
      'Covide',
      'Gondoriz',
      'Moimenta',
      'Ribeira',
      'Rio Caldo',
      'Souto',
      'Valdosende',
      'Vilar da Veiga',
      'Tomar',
      'Além da Ribeira e Pedreira',
      'Asseiceira',
      'Carregueiros',
      'Casais e Alviobeira',
      'Madalena e Beselga',
      'Olalhas',
      'Paialvo',
      'Sabacheira',
      'São Pedro de Tomar',
      'Serra e Junceira',
      'Tomar (São João Baptista) e Santa Maria dos Olivais',
      'Tondela',
      'Barreiro de Besteiros e Tourigo',
      'Campo de Besteiros',
      'Canas de Santa Maria',
      'Caparrosa e Silvares',
      'Castelões',
      'Dardavaz',
      'Ferreirós do Dão',
      'Guardão',
      'Lajeosa do Dão',
      'Lobão da Beira',
      'Molelos',
      'Mouraz e Vila Nova da Rainha',
      'Parada de Gonta',
      'Santiago de Besteiros',
      'São João do Monte e Mosteirinho',
      'São Miguel do Outeiro e Sabugosa',
      'Tonda',
      'Tondela e Nandufe',
      'Vilar de Besteiros e Mosteiro de Fráguas',
      'Torre de Moncorvo',
      'Açoreira',
      'Adeganha e Cardanha',
      'Cabeça Boa',
      'Carviçais',
      'Castedo',
      'Felgar e Souto da Velha',
      'Felgueiras e Maçores',
      'Horta da Vilariça',
      'Larinho',
      'Lousa',
      'Mós',
      'Torre de Moncorvo',
      'Urrós e Peredo dos Castelhanos',
      'Torres Novas',
      'Assentiz',
      'Brogueira, Parceiros de Igreja e Alcorochel',
      'Chancelaria',
      'Meia Via',
      'Olaia e Paço',
      'Pedrógão',
      'Riachos',
      'Torres Novas (Santa Maria, Salvador e Santiago)',
      'Torres Novas (São Pedro), Lapas e Ribeira Branca',
      'Zibreira',
      'Torres Vedras',
      'A dos Cunhados e Maceira',
      'Campelos e Outeiro da Cabeça',
      'Carvoeira e Carmões',
      'Dois Portos e Runa',
      'Freiria',
      'Maxial e Monte Redondo',
      'Ponte do Rol',
      'Ramalhal',
      'Santa Maria, São Pedro e Matacães',
      'São Pedro da Cadeira',
      'Silveira',
      'Turcifal',
      'Ventosa',
      'Trancoso',
      'Aldeia Nova',
      'Castanheira',
      'Cogula',
      'Cótimos',
      'Fiães',
      'Freches e Torres',
      'Granja',
      'Guilheiro',
      'Moimentinha',
      'Moreira de Rei',
      'Palhais',
      'Póvoa do Concelho',
      'Reboleiro',
      'Rio de Mel',
      'Tamanhos',
      'Torre do Terrenho, Sebadelhe da Serra e Terrenho',
      'Trancoso (São Pedro e Santa Maria) e Souto Maior',
      'Valdujo',
      'Vale do Seixo e Vila Garcia',
      'Vila Franca das Naves e Feital',
      'Vilares e Carnicães',
      'Trofa',
      'Alvarelhos e Guidões',
      'Bougado (São Martinho e Santiago)',
      'Coronado (São Romão e São Mamede)',
      'Covelas',
      'Muro',
      'V',
      'Vagos',
      'Calvão',
      'Fonte de Angeão e Covão do Lobo',
      'Gafanha da Boa Hora',
      'Ouca',
      'Ponte de Vagos e Santa Catarina',
      'Santo André de Vagos',
      'Sosa',
      'Vagos e Santo António',
      'Vale de Cambra',
      'Arões',
      'Cepelos',
      'Junqueira',
      'Macieira de Cambra',
      'Roge',
      'São Pedro de Castelões',
      'Vila Chã, Codal e Vila Cova de Perrinho',
      'Valença',
      'Boivão',
      'Cerdal',
      'Fontoura',
      'Friestas',
      'Gandra e Taião',
      'Ganfei',
      'Gondomil e Sanfins',
      'São Julião e Silva',
      'São Pedro da Torre',
      'Valença, Cristelo Covo e Arão',
      'Verdoejo',
      'Valongo',
      'Alfena',
      'Campo e Sobrado',
      'Ermesinde',
      'Valongo',
      'Valpaços',
      'Água Revés e Crasto',
      'Algeriz',
      'Bouçoães',
      'Canaveses',
      'Carrazedo de Montenegro e Curros',
      'Ervões',
      'Fornos do Pinhal',
      'Friões',
      'Lebução, Fiães e Nozelos',
      'Padrela e Tazem',
      'Possacos',
      'Rio Torto',
      'Santa Maria de Emeres',
      'Santa Valha',
      'Santiago da Ribeira de Alhariz',
      'São João da Corveira',
      'São Pedro de Veiga de Lila',
      'Serapicos',
      'Sonim e Barreiros',
      'Tinhela e Alvarelhos',
      'Vales',
      'Valpaços e Sanfins',
      'Vassal',
      'Veiga de Lila',
      'Vilarandelo',
      'Velas',
      'Manadas (Santa Bárbara)',
      'Norte Grande (Neves)',
      'Rosais',
      'Santo Amaro',
      'Urzelina (São Mateus)',
      'Velas (São Jorge)',
      'Vendas Novas',
      'Landeira',
      'Vendas Novas',
      'Viana do Alentejo',
      'Aguiar',
      'Alcáçovas',
      'Viana do Alentejo',
      'Viana do Castelo',
      'Afife',
      'Alvarães',
      'Amonde',
      'Anha',
      'Areosa',
      'Barroselas e Carvoeiro',
      'Cardielos e Serreleis',
      'Carreço',
      'Castelo do Neiva',
      'Chafé',
      'Darque',
      'Freixieiro de Soutelo',
      'Geraz do Lima (Santa Maria, Santa Leocádia e Moreira) e Deão',
      'Lanheses',
      'Mazarefes e Vila Fria',
      'Montaria',
      'Mujães',
      'Nogueira, Meixedo e Vilar de Murteda',
      'Outeiro',
      'Perre',
      'Santa Marta de Portuzelo',
      'São Romão de Neiva',
      'Subportela, Deocriste e Portela Susã',
      'Torre e Vila Mou',
      'Viana do Castelo (Santa Maria Maior e Monserrate) e Meadela',
      'Vila de Punhe',
      'Vila Franca',
      'Vidigueira',
      'Pedrógão',
      'Selmes',
      'Vidigueira',
      'Vila de Frades',
      'Vieira do Minho',
      'Anissó e Soutelo',
      'Anjos e Vilar do Chão',
      'Caniçada e Soengas',
      'Cantelães',
      'Eira Vedra',
      'Guilhofrei',
      'Louredo',
      'Mosteiro',
      'Parada de Bouro',
      'Pinheiro',
      'Rossas',
      'Ruivães e Campos',
      'Salamonde',
      'Tabuaças',
      'Ventosa e Cova',
      'Vieira do Minho',
      'Vila de Rei',
      'Fundada',
      'São João do Peso',
      'Vila de Rei',
      'Vila do Bispo',
      'Barão de São Miguel',
      'Budens',
      'Sagres',
      'Vila do Bispo e Raposeira',
      'Vila do Conde',
      'Árvore',
      'Aveleda',
      'Azurara',
      'Bagunte, Ferreiró, Outeiro Maior e Parada',
      'Fajozes',
      'Fornelo e Vairão',
      'Gião',
      'Guilhabreu',
      'Junqueira',
      'Labruge',
      'Macieira da Maia',
      'Malta e Canidelo',
      'Mindelo',
      'Modivas',
      'Retorta e Tougues',
      'Rio Mau e Arcos',
      'Touguinha e Touguinhó',
      'Vila Chã',
      'Vila do Conde',
      'Vilar de Pinheiro',
      'Vilar e Mosteiró',
      'Vila do Porto',
      'Almagreira',
      'Santa Bárbara',
      'Santo Espírito',
      'São Pedro',
      'Vila do Porto',
      'Vila Flor',
      'Assares e Lodões',
      'Benlhevai',
      'Candoso e Carvalho de Egas',
      'Freixiel',
      'Roios',
      'Samões',
      'Sampaio',
      'Santa Comba de Vilariça',
      'Seixo de Manhoses',
      'Trindade',
      'Vale Frechoso',
      'Valtorno e Mourão',
      'Vila Flor e Nabo',
      'Vilas Boas e Vilarinho das Azenhas',
      'Vila Franca de Xira',
      'Alhandra, São João dos Montes e Calhandriz',
      'Alverca do Ribatejo e Sobralinho',
      'Castanheira do Ribatejo e Cachoeiras',
      'Póvoa de Santa Iria e Forte da Casa',
      'Vialonga',
      'Vila Franca de Xira',
      'Vila Franca do Campo',
      'Água de Alto',
      'Ponta Garça',
      'Ribeira das Tainhas',
      'Ribeira Seca',
      'Vila Franca do Campo (São Miguel)',
      'Vila Franca do Campo (São Pedro)',
      'Vila Nova da Barquinha',
      'Atalaia',
      'Praia do Ribatejo',
      'Tancos',
      'Vila Nova da Barquinha',
      'Vila Nova de Cerveira',
      'Campos e Vila Meã',
      'Candemil e Gondar',
      'Cornes',
      'Covas',
      'Gondarém',
      'Loivo',
      'Mentrestido',
      'Reboreda e Nogueira',
      'Sapardos',
      'Sopo',
      'Vila Nova de Cerveira e Lovelhe',
      'Vila Nova de Famalicão',
      'Antas e Abade de Vermoim',
      'Arnoso (Santa Maria e Santa Eulália) e Sezures',
      'Avidos e Lagoa',
      'Bairro',
      'Brufe',
      'Carreira e Bente',
      'Castelões',
      'Cruz',
      'Delães',
      'Esmeriz e Cabeçudos',
      'Fradelos',
      'Gavião',
      'Gondifelos, Cavalões e Outiz',
      'Joane',
      'Landim',
      'Lemenhe, Mouquim e Jesufrei',
      'Louro',
      'Lousado',
      'Mogege',
      'Nine',
      'Oliveira (Santa Maria)',
      'Oliveira (São Mateus)',
      'Pedome',
      'Pousada de Saramagos',
      'Requião',
      'Riba de Ave',
      'Ribeirão',
      'Ruivães e Novais',
      'Seide',
      'Vale (São Cosme), Telhado e Portela',
      'Vale (São Martinho)',
      'Vermoim',
      'Vila Nova de Famalicão e Calendário',
      'Vilarinho das Cambas',
      'Vila Nova de Foz Côa',
      'Almendra',
      'Castelo Melhor',
      'Cedovim',
      'Chãs',
      'Custóias',
      'Freixo de Numão',
      'Horta',
      'Muxagata',
      'Numão',
      'Santa Comba',
      'Sebadelhe',
      'Seixas',
      'Touça',
      'Vila Nova de Foz Coa',
      'Vila Nova de Gaia',
      'Arcozelo',
      'Avintes',
      'Canelas',
      'Canidelo',
      'Grijó e Sermonde',
      'Gulpilhares e Valadares',
      'Madalena',
      'Mafamude e Vilar do Paraíso',
      'Oliveira do Douro',
      'Pedroso e Seixezelo',
      'Sandim, Olival, Lever e Crestuma',
      'Santa Marinha e São Pedro da Afurada',
      'São Félix da Marinha',
      'Serzedo e Perosinho',
      'Vilar de Andorinho',
      'Vila Nova de Paiva',
      'Pendilhe',
      'Queiriga',
      'Touro',
      'Vila Cova à Coelheira',
      'Vila Nova de Paiva, Alhais e Fráguas',
      'Vila Nova de Poiares',
      'Arrifana',
      'Lavegadas',
      'Poiares (Santo André)',
      'São Miguel de Poiares',
      'Vila Pouca de Aguiar',
      'Alfarela de Jales',
      'Alvão',
      'Bornes de Aguiar',
      'Bragado',
      'Capeludos',
      'Pensalvos e Parada de Monteiros',
      'Sabroso de Aguiar',
      'Soutelo de Aguiar',
      'Telões',
      'Tresminas',
      'Valoura',
      'Vila Pouca de Aguiar',
      'Vreia de Bornes',
      'Vreia de Jales',
      'Vila Real',
      'Abaças',
      'Adoufe e Vilarinho de Samardã',
      'Andrães',
      'Arroios',
      'Borbela e Lamas de Olo',
      'Campeã',
      'Constantim e Vale de Nogueiras',
      'Folhadela',
      'Guiães',
      'Lordelo',
      'Mateus',
      'Mondrões',
      'Mouçós e Lamares',
      'Nogueira e Ermida',
      'Parada de Cunhos',
      'Pena, Quintã e Vila Cova',
      'São Tomé do Castelo e Justes',
      'Torgueda',
      'Vila Marim',
      'Vila Real',
      'Vila Real de Santo António',
      'Monte Gordo',
      'Vila Nova de Cacela',
      'Vila Real de Santo António',
      'Vila Velha de Ródão',
      'Fratel',
      'Perais',
      'Sarnadas de Ródão',
      'Vila Velha de Ródão',
      'Vila Verde',
      'Aboim da Nóbrega e Gondomar',
      'Atiães',
      'Cabanelas',
      'Carreiras (São Miguel) e Carreiras (Santiago)',
      'Cervães',
      'Coucieiro',
      'Dossãos',
      'Escariz (São Mamede) e Escariz (São Martinho)',
      'Esqueiros, Nevogilde e Travassós',
      'Freiriz',
      'Gême',
      'Lage',
      'Lanhas',
      'Loureira',
      'Marrancos e Arcozelo',
      'Moure',
      'Oleiros',
      'Oriz (Santa Marinha) e Oriz (São Miguel)',
      'Parada de Gatim',
      'Pico',
      'Pico de Regalados, Gondiães e Mós',
      'Ponte',
      'Prado (São Miguel)',
      'Ribeira do Neiva',
      'Sabariz',
      'Sande, Vilarinho, Barros e Gomide',
      'Soutelo',
      'Turiz',
      'Vade',
      'Valbom (São Pedro), Passô e Valbom (São Martinho)',
      'Valdreu',
      'Vila de Prado',
      'Vila Verde e Barbudo',
      'Vila Viçosa',
      'Bencatel',
      'Ciladas',
      'Nossa Senhora da Conceição e São Bartolomeu',
      'Pardais',
      'Vimioso',
      'Algoso, Campo de Víboras e Uva',
      'Argozelo',
      'Caçarelhos e Angueira',
      'Carção',
      'Matela',
      'Pinelo',
      'Santulhão',
      'Vale de Frades e Avelanoso',
      'Vilar Seco',
      'Vimioso',
      'Vinhais',
      'Agrochão',
      'Candedo',
      'Celas',
      'Curopos e Vale de Janeiro',
      'Edral',
      'Edrosa',
      'Ervedosa',
      'Moimenta e Montouto',
      'Nunes e Ousilhão',
      'Paçó',
      'Penhas Juntas',
      'Quirás e Pinheiro Novo',
      'Rebordelo',
      'Santalha',
      'Sobreiro de Baixo e Alvaredos',
      'Soeira, Fresulfe e Mofreita',
      'Travanca e Santa Cruz',
      'Tuizelo',
      'Vale das Fontes',
      'Vila Boa de Ousilhão',
      'Vila Verde',
      'Vilar de Lomba e São Jomil',
      'Vilar de Ossos',
      'Vilar de Peregrinos',
      'Vilar Seco de Lomba',
      'Vinhais',
      'Viseu',
      'Abraveses',
      'Barreiros e Cepões',
      'Boa Aldeia, Farminhão e Torredeita',
      'Bodiosa',
      'Calde',
      'Campo',
      'Cavernães',
      'Cota',
      'Coutos de Viseu',
      'Faíl e Vila Chã de Sá',
      'Fragosela',
      'Lordosa',
      'Mundão',
      'Orgens',
      'Povolide',
      'Ranhados',
      'Repeses e São Salvador',
      'Ribafeita',
      'Rio de Loba',
      'Santos Evos',
      'São Cipriano e Vil de Souto',
      'São João de Lourosa',
      'São Pedro de France',
      'Silgueiros',
      'Viseu',
      'Vizela',
      'Caldas de Vizela (São Miguel e São João)',
      'Infias',
      'Santa Eulália',
      'Tagilde e Vizela (São Paio)',
      'Vizela (Santo Adrião)',
      'Vouzela',
      'Alcofra',
      'Cambra e Carvalhal de Vermilhas',
      'Campia',
      'Fataunços e Figueiredo das Donas',
      'Fornelo do Monte',
      'Queirã',
      'São Miguel do Mato',
      'Ventosa',
      'Vouzela e Paços de Vilharigues'
    ];

    function initDialog() {
      clearDialog();
      for (var i = 0; i < states.length; i++) {
        $('.dialog').append('<div>' + states[i] + '</div>');
      }
    }

    function clearDialog() {
      $('.dialog').empty();
    }
    $('.autocomplete input').click(function() {
      if (!alreadyFilled) {
        $('.dialog').addClass('open');
      }

    });
    $('body').on('click', '.dialog > div', function() {
      $('.autocomplete input').val($(this).text()).focus();
      $('.autocomplete .close').addClass('visible');
      alreadyFilled = true;
    });
    $('.autocomplete .close').click(function() {
      alreadyFilled = false;
      $('.dialog').addClass('open');
      $('.autocomplete input').val('').focus();
      $(this).removeClass('visible');
    });

    function match(str) {
      str = str.toLowerCase();
      clearDialog();
      for (var i = 0; i < states.length; i++) {
        if (states[i].toLowerCase().startsWith(str)) {
          $('.dialog').append('<div>' + states[i] + '</div>');
        }
      }
    }
    $('.autocomplete input').on('input', function() {
      $('.dialog').addClass('open');
      alreadyFilled = false;
      match($(this).val());
    });
    $('body').click(function(e) {
      if (!$(e.target).is("input, .close")) {
        $('.dialog').removeClass('open');
      }
    });
    initDialog();
  });
</script>

<?php
if (!isset($_SESSION['Login'])) {
?>
  <script>
    window.location = "index.php?cmd=loginpage";
  </script>
<?php

}
?>

<br><br>

<?php if ($_SERVER['HTTP_X_REQUESTED_WITH'] == "mgks.os.swv") { ?>
  <div class="container" style="margin-top: -100px;">
  <?php } else { ?>
    <div class="container">
    <?php } ?>
    <br><br>
    <div class="section-title" align="center">
      <p>Publicar anúncio</p>
    </div>

    <div class="row">

      <div class="col-lg-8 col-lg-offset-2">

        <form enctype="multipart/form-data" id="contact-form" method="POST" role="form" autocomplete="off" action="index.php?cmd=ins-prod">

          <div class="messages"></div>

          <div class="controls">

            <div class="col-md-12">
              <div class="form-group">
                <label for="Titulo">Título *</label>
                <input id="Titulo" type="text" name="Titulo" class="form-control" placeholder="ex. iPhone 11 com garantia" required="required" data-error="Firstname is required.">
                <div class="help-block with-errors"></div>
              </div>
            </div>

            <div class="col-md-12">
              <div class="form-group">
                <label for="form_lastname">Categoria *</label>

                <select class="form-control" name="CodCat" id="CodCat" required="required">
                  <option value=''>Selecionar Categoria</option>
                  <?php
                  $sql = "select * from Categoria";
                  $res = $lig->query($sql);
                  while ($lin = $res->fetch_array()) {
                    echo "<option value=", $lin['CodCat'], ">", $lin['CatDgs'], "</option>";
                  }
                  ?>
                </select>

              </div>
            </div>

            <div class="col-md-6" style="margin-right: 400px;">
              <div class="form-group">
                <label for="Preco">Preço do Anúncio *</label>
                <input id="Preco" type="number" step="0.01" name="Preco" class="form-control" placeholder="0" required="required" autofocus="autofocus" />
                <span class="unit">€</span>

              </div>
            </div>

            <center>
              <div class="row" id="imgs">

                <div class="form-group">
                  <label for="01">
                    <div class="upload-wrap">

                      <div class="uploadpreview 01">
                        <img id='img01' src="./imgs/no_image.png" width="145" height="145">
                      </div>

                      <input type="hidden" name="MAX_FILE_SIZE" value="300000000" />
                      <input id="01" type="file" name="Foto1" accept="image/*">
                    </div>

                  </label>

                  <label for="02">
                    <div class="upload-wrap">
                      <div class="uploadpreview 02">
                        <img id='img02' src="./imgs/no_image.png" width="145" height="145">
                      </div>
                      <input type="hidden" name="MAX_FILE_SIZE" value="300000000" />
                      <input id="02" type="file" name="Foto2" accept="image/*">
                    </div>
                  </label>


                  <label for="03">
                    <div class="upload-wrap">
                      <div class="uploadpreview 03">
                        <img id='img03' src="./imgs/no_image.png" width="145" height="145">
                      </div>
                      <input type="hidden" name="MAX_FILE_SIZE" value="300000000" />
                      <input id="03" type="file" name="Foto3" accept="image/*">
                    </div>
                  </label>

                  <label for="04">
                    <div class="upload-wrap">
                      <div class="uploadpreview 04">
                        <img id='img04' src="./imgs/no_image.png" width="145" height="145">
                      </div>
                      <input type="hidden" name="MAX_FILE_SIZE" value="300000000" />
                      <input id="04" type="file" name="Foto4" accept="image/*">
                    </div>
                  </label>

                  <label for="05">
                    <div class="upload-wrap">
                      <div class="uploadpreview 05">
                        <img id='img05' src="./imgs/no_image.png" width="145" height="145">
                      </div>
                      <input type="hidden" name="MAX_FILE_SIZE" value="300000000" />
                      <input id="05" type="file" name="Foto5" accept="image/*">
                    </div>
                  </label>

                  <label for="06">
                    <div class="upload-wrap">
                      <div class="uploadpreview 06">
                        <img id='img06' src="./imgs/no_image.png" width="145" height="145">
                      </div>
                      <input type="hidden" name="MAX_FILE_SIZE" value="300000000" />
                      <input id="06" type="file" name="Foto6" accept="image/*">
                    </div>
                  </label>

                </div>
              </div>
          </div>
          </center>
          <div class="col-md-6">
            <div class="form-group">
              <label for="Localizacao">Localização *</label>


              <?php if ($_SERVER['HTTP_X_REQUESTED_WITH'] == "mgks.os.swv") { ?>      
                <div class="autocomplete">
              <?php } else { ?>
                <div class="autocomplete" style="width: 700px;" >
              <?php } ?>
                <input type="text" name="Localizacao" placeholder="Localização do anúncio..." required="required">
                <span class="close">Cancelar</span>
                <div class="dialog">
                </div>
              </div>

            </div>
          </div>

          <div class="col-md-12">
            <div class="form-group">
              <label for="Descricao">Descrição *</label>
              <textarea style="resize: none" id="Descricao" maxlength="800" minlength="30" name="Descricao" class="form-control" placeholder="Escreve o que gostarias de ler se fosses tu a ver este anúncio" rows="12" required="required" data-error="Please,leave us a message."></textarea>
              <div class="help-block with-errors"></div>
            </div>
          </div>
          <div class="col-md-12">
            <input type="submit" class="btn btn-success btn-send" value="Publicar Anúncio">
          </div>
          <br>
      </div>
      </form>
    </div>
    </div>
  </div>

  <script>
    $(function() {
      $("#contact-form").validator();
      $("#contact-form").on("submit", function(e) {
        if (!e.isDefaultPrevented()) {
          var url = "contact.php";

          var messageAlert = "alert-success";
          var messageText =
            "Your message was sent, thank you. I will get back to you soon.";

          var alertBox =
            '<div class="alert ' +
            messageAlert +
            ' alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>' +
            messageText +
            "</div>";

          if (messageAlert && messageText) {
            $("#contact-form").find(".messages").html(alertBox);
            $("#contact-form")[0].reset();
          }
          return false;
        }
      });
    });

    $('.upload-wrap input[type=file]').change(function() {
      var id = $(this).attr("id");
      var img = document.getElementById("img" + id);
      img.style.visibility = 'hidden';
      var newimage = new FileReader();
      newimage.readAsDataURL(this.files[0]);
      newimage.onload = function(e) {
        $('.uploadpreview.' + id).css('background-image', 'url(' + e.target.result + ')');

      }
    });
  </script>

  <style>
    .uploadpreview {
      width: 150px;
      height: 150px;
      display: block;
      border: 2px solid #ccc;
      margin: 0 auto 5px;
      background-size: 100% auto;
      background-repeat: no-repeat;
      background-position: center;
      cursor: pointer;
    }

    .upload-wrap {

      width: 250px;
      margin-top: 10px;
    }

    input[type="file"] {
      display: none;
    }

    .input-box {
      position: relative;
    }

    input {
      display: block;
      border: 1px solid #d7d6d6;
      background: #fff;
      padding: 10px 10px 10px 20px;
      width: 195px;
    }

    .unit {
      position: absolute;
      display: block;
      left: 305px;
      top: 32px;
      z-index: 9;
    }

    body {
      background: #f5f5f5;
    }

    .autocomplete {
      background: #fff;
      position: relative;
      box-shadow: 0 0 2px rgba(0, 0, 0, 0.12), 0 2px 2px rgba(0, 0, 0, 0.24);
    }

    .autocomplete .close {
      position: absolute;
      font-size: 13px;
      z-index: 10;
      top: 10px;
      left: calc(100% - 50px);
      color: #aaa;
      cursor: pointer;
      display: none;
    }

    .autocomplete .close.visible {
      display: block;
    }

    input {
      padding: 10px 10px;
      font-weight: 300;
      width: 100%;
      border: none;
      outline: none;
      font-size: 14px;
      color: #666;
    }

    .dialog {
      width: 100%;
      display: none;
      min-height: 40px;
      max-height: 330px;
      overflow: scroll;
      border-top: 1px solid #f4f4f4;
    }

    .dialog.open {
      display: block;
    }

    .dialog div {
      padding: 20px 10px;
      font-size: 13px;
      cursor: pointer;
      transition: all 0.2s;
    }

    .dialog div:hover {
      background: #f2f2f2;
    }
  </style>